### ISSUE TITLE
[ Debugging ] Natvis cannot be viewed in tooltips

### ISSUE THREAD

**Issue by iwubcode** [microsoft/VSLinux#222] opened 2017-11-10 19:35 UTC
**Problem Description**

Variable 'tooltips' does not properly define natvis (even clicking the 'refresh' button).  You can only view natvis 'visualized view' in the watch window.

**Expected Results**

Viewing natvis in tooltips should be available (maybe as an option?)

**Actual Results**

You cannot view natvis in a tooltip.  It gives the following error (taken from another issue report but I see the same error):

![image](https://user-images.githubusercontent.com/15224722/32675095-4da74b5e-c61b-11e7-956b-cb7fdb6c6720.png)

**Environment**
Visual Studio 2017 15.5 Preview 3
GDB 8.x

**How to reproduce**

* Have a C++ project with natvis defined
* Hover over a variable
* Notice natvis "visualized view" has a red x (and 'refresh' does not work)

**Comment by paulmaybee** [comment] 2018-09-17 21:40
Fixed in the next major release of VS.

**Comment by itodirel** [comment] 2020-03-20 08:09
We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-20 08:09 UTC
Labels: bug understood, fixed
