### ISSUE TITLE
Adding "../" to the include path produces a weird "-I" directive

### ISSUE THREAD

**Issue by rubu** [Microsoft/VSLinux#47] opened 2016-09-17 17:30 UTC
Adding "../" produces a weird "-I" directive:

![image](https://cloud.githubusercontent.com/assets/1997432/18609872/323e313e-7d15-11e6-8792-b874d660dd34.png)

Instead of the expected value "/home/rudolfs/projects/include_path_test/../" it produces "/home/rudolfs/projects/include_path_test/../../include_path_test".

While for example using "../test/" works as expected and produces "/home/rudolfs/projects/include_path_test/../test"

![image](https://cloud.githubusercontent.com/assets/1997432/18609885/96360cac-7d15-11e6-93e9-329a9e447274.png)

**Comment by TimKendall76** [comment] 2016-09-22 16:08
I am having similar problems. When building, the task "MakeClCommandLine" is not resolving the correct path for source files. For example, if the source cpp file is in a directory one level up and down into another folder you get something like this:
2>                     Output Item(s):
2>                         RemoteClCompile=
2>                             /root/projects/LinDemo/../MainDemoSource/TcimDemo.cpp
2>                                     CommandLine=-c -x c /root/projects/LinDemo/../MainDemoSource/TcimDemo.cpp -I /root/projects/LinDemo/../MainDemoInclude -g2 -gdwarf-2 -o "/root/projects/LinDemo/obj/x86/Debug/TcimDemo.o" -Wall -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fexceptions

In this case the source file is NOT compiled because the path is invalid, or at least my gcc doesn't like it.

**Comment by lgolding** [comment] 2016-09-26 17:50
Yes, I can repro @rubu 's bug:

* Adding `../` to Additional Include Directories results in `-I "/home/larry/projects/include-path-test/../../include-path-test"`, (which would resolve to `/home/larry/include-path-test`), but...
* Adding `../test` results in `-I "/home/larry/projects/include-path-test/../test"`, (which would resolve to `/home/larry/projects/test`).

But even in the case where the include path is _constructed_ correctly, this won't work because we don't copy the contents of the `../test` directory to the target.

**Comment by lgolding** [comment] 2016-09-29 20:31
@rubu I don't yet know the root cause of the odd include path on the command line. But I can tell you that if you need to reference a header file from outside your project tree, you can do so by explicitly adding the header file to the project file. (I see from your screen shots that the header file is not mentioned in your project.) If you do that, the solution builds successfully (and you'll see the correct include path on the g++ command line).

I have an example zipped up but I can't paste it into the GitHub issue. I'll mail it to you.

@TimKendall76 I haven't yet tried your scenario where the "outside-the-directory" file is a source file instead of a header file.

@robotdad FYI

**Comment by rubu** [comment] 2016-09-29 21:00
@lgolding I already reported https://github.com/Microsoft/VSLinux/issues/46 where given a certain folder structure including the headers and sources from external directories also fails, so I just hoped I could get around it with this "../" trick but sadly not:) This bug is more of an informative nature - in real world of course I'd have the header files referenced in the project.

**Comment by cthulhua** [comment] 2016-11-15 21:46
This has been fixed, and will be in the next release.

**Closed by cthulhua** 2016-11-15 21:46 UTC
Labels: bug
