### ISSUE TITLE
A makefile project build fails when 'Remote Build Outputs' setting is set with relative path.

### ISSUE THREAD

**Issue by simbi11** [microsoft/VSLinux#99] opened 2017-01-28 18:41 UTC
* A brief description
A makefile project build fails when 'Remote Build Outputs' setting is set with relative path.

makefile project settings:
  Remote Build Root Directory: ~/projects
  Remote Build Project Directory: $(RemoteRootDir)/$(ProjectName)
  Remote Build Outputs: $(RemoteProjectDir)/file

When 'Remote Build Root Directory' is set with full path (for example: /home/user/projects), it works fine.
When 'Remote Build Outputs' is set with full path (for example: /home/user/projects/project/file), it works fine too.

* Expected results
'Remote Build Outputs' works with relative paths too.

* Actual results (with build output window contents if applicable)
Error in VS output window:
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Makefile.Targets(128,5): warning : Cannot copy file '~/projects/project/file', file not found on the remote system.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
linux: ubuntu16.10
VC++ version: 14.0.28002.0

**Comment by allanhaywood** [comment] 2017-04-04 23:21
I am also seeing this same issue.
@simbi11 Thanks for the tip that a full path works.

I am running on Ubuntu 14.04
Visual Studio 15.0.26228.10
Visual C++ for Linux Development   1.0.6

**Comment by alexeykuzmin0** [comment] 2017-04-09 10:28
See the same issue with WSL system.
Visual Studio 15.1.26403.0
Visual C++ for Linux Development 1.0.6
WSL system thinks its Ubuntu 14.04.5, but in fact it's run in Windows 10.1607.14393.953.

**Comment by MrSparc** [comment] 2017-10-05 23:25
I'm experiencing this same issue with relative path (~/...) Using full path works as expected:
Visual Studio Community 2017 (15.3.5)
Visual C++ for Linux Development - 1.0.7
Hyper-V image running Ubuntu Server 14.05

**Comment by HenriSocha** [comment] 2018-07-16 23:37
I found and am fixing a variation of this issue. In my case, I am referring to `<RemoteProjectDir>` which is used by `<RemoteBuildOutputs>` and other items. 
If you look in the .vcxproj file you see:
`<PropertyGroup>` ...
`<RemoteBuildOutputs>$(RemoteProjectDir)...</RemoteBuildOutputs>`
...
`<RemoteProjectDir>$(RemoteRootDir)/.../$(ProjectName)</RemoteProjectDir>`
... `</PropertyGroup>`
All the ... is various stuff left out and not, of itself, relevant.

Moving the `<RemoteProjectDir>` line **before** its first use, resolves the problem!
Could it be your use for the debug path has the same problem?

Now, to get an update to Visual Studio so that, when a .vcxproj file is generated or modified, 
Variables are defined before first use.  sigh

**Comment by itodirel** [comment] 2020-03-24 06:17
This is a dupe of #68

**Closed by itodirel** 2020-03-24 06:17 UTC
Labels: investigating
