### ISSUE TITLE
Public Project Include Directories not working with SharedItems Project

### ISSUE THREAD

**Issue by noujaimc** [microsoft/VSLinux#277] opened 2018-04-05 13:04 UTC
Using : Visual Studio 2017 15.7 Preview  2

When referencing a sharedItems project with a project(static or dynamic) with source files, the Public Project Include Directories does not translate well when linked with a application.  I attached an example below. I was expecting this to compile and run :

[ConsoleApplication.zip](https://github.com/Microsoft/VSLinux/files/1880052/ConsoleApplication.zip)

Thank you !

**Comment by itodirel** [comment] 2018-04-05 20:46
@yuehuang010 Felix can you take a look?

**Comment by yuehuang010** [comment] 2018-04-12 18:08
Taking a look.

**Comment by yuehuang010** [comment] 2018-04-17 21:04
I have found the issue, but the solution is quiet complex, so it won't be fixed in 15.7 timeframe.

**Comment by itodirel** [comment] 2019-01-18 09:02
@yuehuang010 any updates?

**Comment by yuehuang010** [comment] 2019-01-19 00:14
Someone broke our internal tests.
<_<
>_>
2>    Target "_CopySources" skipped, due to false condition; ('$(RequireRemoteConnection)' == 'true' and '$(ResolvedRemoteTarget)' != '') was evaluated as ('' == 'true' and '' != '').
"_CopySources" is used to passed ProjectPublicIncludePath and RemoteIncludePath over P2P Recipe.

**Comment by yuehuang010** [comment] 2019-01-19 00:18
+ @elizabethmorrow

**Comment by yuehuang010** [comment] 2019-01-19 00:49
I downloaded the sample app.  There are few additional issues.
1) Public Project Include Paths should work "include", To workaround, you change it to "./include".
2) libSharedLibrary.so isn't passed to ld from P2P.  New bug: Remove the $(_LinkImportLibraryTemp) in the condition as it is always empty.  [VSINSTALLDIR]MSBuild\Microsoft\VC\v160\Application Type\Linux\1.0\Linux.targets:
Before:
```<_LibFullPath Condition="'$(ConfigurationType)'=='DynamicLibrary' and '$(IgnoreImportLibrary)'!='true' and '$(_LinkImportLibraryTemp)' != ''">$(ResolvedTargetPath)</_LibFullPath>```
After.
```<_LibFullPath Condition="'$(ConfigurationType)'=='DynamicLibrary' and '$(IgnoreImportLibrary)'!='true'">$(ResolvedTargetPath)</_LibFullPath>```

**Comment by itodirel** [comment] 2020-03-24 04:54
Hi, we are not planning on supporting this, please open a suggestion for us on the Developer Community for broader Public Include Directories support. The suggestions given by Felix should work for you as a workaround.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-24 04:54 UTC
Labels: bug
