### ISSUE TITLE
How to add additional sources to copy?

### ISSUE THREAD

**Issue by AliAskari** [microsoft/VSLinux#202] opened 2017-10-24 20:17 UTC
* A brief description

The new CMake integration in Visual Studio copies all files from the root of the project to the remote Linux machine. My build depends on some files that are not in the root of the project. 

For my specific use case, I am using [Conan](https://conan.io/) as my dependency manager and I have 8 different profiles with considerably different options. These files are source controlled in my project but they are not under the root source path as I don't want to clutter the root of my source code with these profile files. 

* Expected results

Have an option in `CMakeSettings.json` to specify additional sources that should be copied to the remote machine. 

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

 Visual Studio Preview 15.5.0 preview 2.0
 RHEL 7.4
 gcc 4.8
 Both x86 and x86_64

* Steps required to reproduce the error

* Required packages and commands to install

To install conan you must have python and pip installed.

`python -m pip install conan`

**Comment by robotdad** [comment] 2017-11-01 15:17
So you have libraries on your Windows machine that you want to place onto your Linux machine. You want to do this without using a library manager on the Linux machine. These libraries are in different locations for different projects, but are not in the folders that the project source is in. 

The way open folder works in VS (cmake or not) is it is that folder. There isn't a notion of managing things in other folders. Sure you can set include paths and things to places outside the current folder, but as you've found you can't then take actions on those folders. Even our [remote tasks](http://aka.ms/vsremotetasks) that do support copy do so at the level of the folder you opened, not against an arbitrary other folder. Tasks may still be the answer for you though.

One idea would be you could write a script that would say run rsync against your local folders on Windows to sync them to Linux. You could then create a task in VS to run that script. Another approach would be a remote task in VS to invoke conan on the remote machine to manage the libraries there.

**Comment by AliAskari** [comment] 2017-11-03 05:04
Thanks for the detailed answer. I think there is a misunderstanding here but I have gotten the answer to my question. I am using Conan natively on my Linux machine so there is no need to rsync headers/libs, the files are already there. I just have to rsync the Conan profiles from my Windows machine to the Linux machine. Thanks.

I have another issue that is related to the current problem. I can build my projects on the Linux machine with CMake and the Open folder feature but since the libraries and headers are on the remote Linux machine I don't get the Intellisense features for those headers. I am getting a red line under my includes with the following message:

    cannot open source file "path/to/header.h"

Do you have any tips on how to solve this problem?

Just note that I can successfully build and debug my application, it's just the intellisense features that are not working.

**Comment by robotdad** [comment] 2017-11-06 17:52
[This is the current advice for geting your includes](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#includes). I'm going to share our plans for improving this in #215

**Comment by robotdad** [comment] 2017-11-17 21:23
@AliAskari any need to keep this one open or shall I close this now?

**Comment by AliAskari** [comment] 2017-11-19 01:59
@robotdad I looked at the proposed solution and I think it will be of little use for us. 

We are using Conan package manager extensively in our projects and in our current workflow we sometimes update the packages a few times a day (i.e. the project headers change all the time). It will be very annoying to have an extra step just to bring the project headers from the Linux box to Windows for intellisense to work.

When I first heard of this feature I assumed you 

- First run CMake on windows for that project to get project headers/dependencies/... so that we have full intellisense support. This could be done by adding a few temp env_variables to the shell that is running the CMake on Windows to simulate a Linux dev environment. 

- Then you copy files to the Linux box and run CMake and ...

Also if running CMake on Windows is not an option, is not possible to gather enough information about the target on the Linux machine using CMake server to pull the headers from the Linux box to Windows?

Please feel free to close this issue. We can continue the discussion in the other issue.

**Comment by itodirel** [comment] 2020-03-25 06:27
This seems like an important scenario that could be a blocker if we don't support, tracking using: https://developercommunity.visualstudio.com/idea/962034/allow-a-way-to-copy-additional-files-from-windows.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-25 06:27 UTC
Labels: discussion
