### ISSUE TITLE
Deleting a remote connection that was used in a project leads to unexpected behaviour

### ISSUE THREAD

**Issue by ozzynator** [Microsoft/VSLinux#326] opened 2018-08-23 09:17 UTC
Hello,
When I try to build, VS for Linux asks me to provide an SSH connection. I have Ubuntu bash for Windows running with ssh enabled, so I enter "localhost" with respective username and password. Visual studio connects to the ubuntu bash and syncs intellisense data and some things.
Then, the following comes up:

1>------ Build started: Project: myproject, Configuration: Debug x64 ------
1>Validating sources
1>Copying sources remotely to '192.168.178.43'
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(157,5): error : Could not find the credentials for remote machine or device '-373503931;192.168.178.43 (username=, port=22, authentication=Password)'. Please select a different remote machine target.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(157,5): error MSB4018: The "CopySources" task failed unexpectedly.

------------------------------

The problem is, that I removed the remote connection that I used a while ago. Visual studio then sets the Remote Build Machine entry in the project settings to something invalid and will not refresh it when you change the remote machine in the visual studio settings (not the project settings). 
This is extra confusing when visual studio asks you for a connection during building but then does not try to use it!
For reproduction, see my next comment.

------------------------------

Microsoft Visual Studio Community 2017 
Version 15.8.1
VisualStudio.15.Release/15.8.1+28010.2003
Microsoft .NET Framework
Version 4.7.03056

Installed Version: Community

Visual C++ 2017   00369-60000-00001-AA727
Microsoft Visual C++ 2017
Visual C++ for Linux Development   1.0.9.27924
Visual C++ for Linux Development

**Comment by ozzynator** [comment] 2018-08-24 07:50
I deleted the file
C:\Users\<User>\Documents\Visual Studio 2017\Default.rdp 
which included the line 
full address:s:192.168.178.43
but with no effect. 

In the project settings, I found the entry 
Remote Build Machine set to -373503931;192.168.178.43 (username=, port=22, authentication=Password)
Removing this resulted in Visual Studio filling it up automatically with 
localhost (username=<TheUserNameIProvidedWhenBuilding!>, port=22, authentication=Password)

When I now delete my localhost connection from the cross platform tab, the entry is set to
Remote Build Macine -951416301;localhost (username=, port=22, authentication=Password)

I have somewhat found the issue and can resolve it now, but as a user you would expect visual studio to actually change the project setting when you build your application and provide a new connection to build it. Decide for yourself if this is a feature or a bug :)

**Comment by itodirel** [comment] 2019-03-19 04:07
if you specifically set the machine in Property Pages, the project is tied to that, that is by design

we're planning an experience where connections are named, and defaults can be selected, closed as is by design, the experience for named/default connections is in our backlog

**Closed by itodirel** 2019-03-19 04:07 UTC
Labels: investigating

**Comment by itodirel** [comment] 2020-03-20 03:26
Default connections is coming in next update of VS.

We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
