### ISSUE TITLE
error while trying to enter break state. Debugging will now stop.

### ISSUE THREAD

**Issue by litronics** [Microsoft/VSLinux#71] opened 2016-11-09 19:58 UTC
when debugging a C++ multithreading application on a raspberry pi (running raspbian jessie) I get the following error message:

> "error while trying to enter break state. Debugging will now stop.
> Unrecognized format of field "level" in result:
> {level=1, addr=0x76d6c360,func=??,arg=[]}"

This error is thrown not all the time and I thought it might be connected to breakepoints but actually it's not. Adding and removing some breakpoints and restart debugging sometimes changes the behavour but that's not guaranteed.

Sometimes the error just goes away by restarting debugging.

Therefore I believe that this is no error in the code itself but somehow connected to multiple threads within the application.

**Comment by rubu** [comment] 2017-01-01 16:07
I can reproduce the same issue with a trivial Raspberry Pi project - the error happens after the call to bcm_host_init() (same as reported here https://github.com/Microsoft/MIEngine/issues/144).

**Comment by rubu** [comment] 2017-01-30 15:08
Is there any way I can help with information in this? Since this issue makes debugging anything VideoCore related on Raspberry Pi impossible I'd be glad to help out. Are there any logs, dumps, etc that can be made?

**Comment by arjankuijpers** [comment] 2017-02-04 02:02
Got the same problem.

**Comment by olivier-haddad** [comment] 2017-02-27 08:27
Same here.
For some strange reason, debugging sometimes works. But rarely so.
I also thought it was connected to breakpoints because somehow it seemed to work more when no breakpoints were set.
It may some kind of race at the beginning and setting breakpoint may modify the timing.

**Comment by craig395** [comment] 2017-03-21 21:45
I also have this error, I think its got something to do with bcm_host_init() as well as it occurs after running a function with that in it, I do have the level as "-1" instead of "1" though. I attached an image of the error.

![vs debug errorpng](https://cloud.githubusercontent.com/assets/14930160/24172289/8e3b7748-0e7f-11e7-9b9f-a0d6fc095672.PNG)

**Comment by arjankuijpers** [comment] 2017-03-26 16:29
Workaround: switch between gdb and gdbserver.

**Comment by MonkahTV** [comment] 2017-04-03 18:24
Same problem here. Good to know it's not me.

RPI/Linux here as well.

**Comment by rubu** [comment] 2017-04-06 07:48
Btw it seems that this is somehow fixed in VS2017 - at least i can safely debug the same project. Not sure why, since it seems to me that there have been no new releases for vslinux, but maybe there are some fixes in the debugger.

**Comment by MonkahTV** [comment] 2017-04-06 14:44
^ You are my hero.

Downloading VS2017 now. Thank you!

**Comment by lukka** [comment] 2018-02-06 19:40
Closing issue. Feel free to reopen if you experience the same problem on a recent version of Visual Studio, thanks.

**Closed by lukka** 2018-02-06 19:40 UTC
Labels: bug, external
