### ISSUE TITLE
WSL support

### ISSUE THREAD

**Issue by MathiasMagnus** [Microsoft/VSLinux#42] opened 2016-09-15 11:05 UTC
- A brief description

Please add support for using the Windows Subsystem for Linux as a "remote" machine.
- Expected results

Using the local instance of Ubuntu, copying source files could be eliminated alltogether, greatly reducing incremental build times while also reducing the complexity of the back-end.

We use the add-in for compiler conformance testing and benchmarking, and for benchmarking it would be great if the very same machine could run the same codes with minimal virtualization overhead for the GCC part (which WSL does not incur). One solution with multiple projects, all referencing the same source file.

SolutionDir/XCompiler.sln
SolutionDir/inc/header.hpp
SolutionDir/src/main.cpp
SolutionDir/VisualC++/VisualC++.vcxproj
SolutionDir/Clang/Clang.vcxproj
SolutionFir/GCC/GCC.vcxproj

I expect to press F7 and see the build output from all compilers. Having a custom script target that invokes each of them, one after the other to benchmark them is the cherry on top (but has nothing to do with the add-in).
- Actual results (with build output window contents if applicable)
- VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
- Steps required to reproduce the error
- Required packages and commands to install

It were nice if the the WSL build would happen either via calling the compiler [from the host](https://msdn.microsoft.com/en-us/commandline/wsl/reference) MSBuild process or if remotely it would invoke a [.Net Core targeted](https://github.com/Microsoft/msbuild/wiki/Building-Testing-and-Debugging-on-.Net-Core-MSBuild) MSBuild instance.

**Comment by robotdad** [comment] 2016-09-15 21:49
This looks like the first public opportunity to explain this. I expect we'll get a blog post up on this with the WSL folks eventually.

The briefest summary:
- You need to install g++, gdb, gdbserver and configure ssh
- In sshd_config, set ‘UsePrivilegeSeparation’ to ‘no’
- You may need to set a port other than 22, and make sure the Windows firewall is open for it
- You don’t have to use the steps for client keys if you enable password auth in sshd_config
- Since you are actually all on one machine here you can [avoid copying files by using project properties](https://blogs.msdn.microsoft.com/vcblog/2016/03/30/visual-c-for-linux-development/#copysources)

Expanded:
Getting WSL working with the VC++ extension
1. Install g++ gdb and gdbserver
2. Setup ssh, 
Edit /etc/ssh/sshd_config
Avoid missing chroot support by changing ‘UsePrivilegeSeparation’ to ‘no’
Optional: Pick a port other than 22 to avoid conflict with other ssh services if they are running in Windows
3. Generate server keys
The default set of keys are dsa, ecdsa, ed25519 and rsa
ssh-keygen –t <type> –f /etc/ssh/ssh_host_<type>_key
For example: ssh-keygen –t dsa –f /etc/ssh/ssh_host_dsa_key
4. Create ~/.ssh
mkdir ~/.ssh
chmod 0755 ~/.ssh
5. Generate client keys so you can connect
ssh-keygen –t <type> -f ~/.ssh/id_<type>
chmod 0755 ~/.ssh/id_*
6. Add at least one of the client keys to the server’s authorized file
cp ~/.ssh/id_<type>.pub ~/.ssh/authorized_keys
To add another: cat ~/.ssh/id_<type>.pub >> ~/.ssh/authorized_keys
7. Start the service
/usr/sbin/sshd
8. In Windows add a new firewall rule to accept connections on the port you chose above (there may be one already but only for the Windows SSH services)
9. Setup your connection from VS as described in our [post](http://aka.ms/vslinux)

**Comment by robotdad** [comment] 2016-09-23 17:57
@MathiasMagnus did you get a chance to try this?

**Comment by robotdad** [comment] 2016-09-23 20:34
A new note on this. I just set this up again on Win 10 version 1607 and found that I did not have to generate the server keys in step 3.

If you want to logon with password instead of cert based auth change PasswordAuthentication to yes in your sshd_config.

When setting this up it helps to initially launch in wsl as  sudo /usr/sbin/sshd -D -d and connect from another ssh client. That will give you debug output to see any errors that may be occurring in establishing a connection. Very helpful for identifying problems in sshd_config.

Once you have this running you can bring the service up/down with sudo service ssh start|stop

**Comment by MathiasMagnus** [comment] 2016-09-27 13:38
Hi!

Sorry for the delay, I have been borderline dead in the past three days with fewer and could not manifest near a keyboard.

I tried the things you hinted, there is just one momentum I cannot get working. It would be nice if I could elide copying the sources, so I set the CopySources to no on a project level. There is just one Source.cpp. However, the paths differ on the Win10 host and the Ubuntu subsystem. How can I make the build system aware of this difference?

```
Windows: C:\Users\Matty\OneDrive\Develop\Tests\Non-CMake\XPlatform_test\GCC_test\Source.cpp
WSL: /mnt/c/Users/Matty/OneDrive/Develop/Tests/Non-CMake/XPlatform_test/GCC_test/Source.cpp
```

The output directory may very well be on the subsystems' path, and only accessible there. I only want to launch it through F5 and Ctrl+F5 anyway (and perhaps see a console with the output, I saw there is a linux console windows available for opening in VS).

**Comment by robotdad** [comment] 2016-09-27 15:09
@MathiasMagnus I have not seen this file truncated error before. Can you zip and attach the file here or send it to vcpplinux-support@microsoft.com?

**Comment by Manouchehri** [comment] 2016-10-09 02:08
Using @robotdad's steps, I was able to get WSL working for VS.

![screenshot 4](https://cloud.githubusercontent.com/assets/7232674/19217234/9789b59c-8da3-11e6-800c-2ff98a6c5c9b.png)

**Comment by Manouchehri** [comment] 2016-10-09 02:33
@robotdad I'm also getting the same `File truncated` error as @MathiasMagnus (with the program above) when I don't have VS copy the sources for me.

**Comment by Manouchehri** [comment] 2016-10-09 02:57
```
1>------ Build started: Project: ConsoleApplication2, Configuration: Debug x64 ------
1>  Validating architecture
1>  Copying sources remotely
1>  Starting remote build
1>  Compiling sources:
1>  main.cpp
1>  Linking objects
1>C:\Users\david\OneDrive\Documents\Visual Studio 2015\Projects\ConsoleApplication2\ConsoleApplication2\obj\x64\Debug\main.o : error : File truncated
1>collect2 : error : ld returned 1 exit status
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========
```

My project files are here: https://davidmanouchehri.visualstudio.com/DefaultCollection/ConsoleApplication2/ConsoleApplication2%20Team/_git/ConsoleApplication2

**Comment by MathiasMagnus** [comment] 2016-11-12 19:51
Any news on solving this issue?

**Comment by robotdad** [comment] 2016-11-16 20:33
@MathiasMagnus you are still getting the file truncated error? I've never seen that before.

**Comment by Manouchehri** [comment] 2016-11-16 20:54
@robotdad I'm still getting it.

**Comment by MathiasMagnus** [comment] 2016-11-17 11:30
Me too. Vanilla Windows 10 (up to date), Ubuntu 16.04 inside the WSL. If I ask the extension not to copy sources AND I point to a path residing in my home (or some place with ordinary NTFS path) it says this error message.

**Comment by robotdad** [comment] 2016-11-17 17:35
OK, we have a good repro here now on the truncation. The issue seems to be specific to mapping to a local directory with copy files set to no with one of our msbuild driven project templates. If you use our makefile template you can actually map to a local directory with WSL just fine. This explains why I hadn't hit this before, I'd been letting the files copy for our console app etc. style projects, but mapping to local directories only when trying larger projects that had build scripts or makefiles.

So root cause is unknown but to avoid this error for now let the console app or other projects copy the files, they can't be in the same location. If you want to avoid copying the files locally use the makefile style project.

**Comment by itodirel** [comment] 2016-11-19 02:47
I believe the file truncated issue might happen because the compile output is in the same location as the local output where the file is to be copied to, so it is overriding itself. One potential fix can be to choose a different path for the remote root project vs the sources. But this would be painful to setup. I will think more in depth on how to fix it. We recently made another fix though, aiming at improving the performance, related to not copying the obj files back to the local machine from the remote one. This copying will be disabled by default, but can be enabled back if wanted. And that should fix this issue as well indirectly. The fix will be available in 1.0.6.

**Comment by robotdad** [comment] 2017-06-19 22:28
We've got an [official post up on how to target WSL](https://blogs.msdn.microsoft.com/vcblog/2017/02/08/targeting-windows-subsystem-for-linux-from-visual-studio/) now so I'm closing this one.

**Closed by robotdad** 2017-06-19 22:28 UTC
Labels: discussion

**Comment by evakili** [comment] 2017-07-09 08:12
Is there any comment about the problem described [here](https://stackoverflow.com/questions/44088855)?

**Comment by yoka791** [comment] 2018-01-10 11:58
How can I change the auto command -std=c++11 to -std=c++0x?

**Comment by itodirel** [comment] 2019-04-17 02:32
Hi @MathiasMagnus @Manouchehri @evakili @yoka791 we're adding native WSL support in 16.1 Preview 2, it works without SSH connections directly on top of WSL

**Comment by MathiasMagnus** [comment] 2019-04-17 11:15
Big thanks for direct WSL support!

I mostly focus on OpenCL and SYCL apps and run them on WSL using POCL and ComputeCpp. A running project is using C11 for host code but IntelliSense in CMake projects does not seem to pick up GNU language standards properly. It's already reported [here](https://developercommunity.visualstudio.com/content/problem/496359/c11-for-loop-init-clause-misparsed-by-intellisense.html). Shall I open an issue here or is developercommunity adequate?
