### ISSUE TITLE
exception of type  "Microsoft.Build.Linux.Shared.ExceptionTTY" was thrown

### ISSUE THREAD

**Issue by GenKnight** [Microsoft/VSLinux#278] opened 2018-04-07 05:28 UTC
I use  vs2017 to debug a linux cpp  demo(vs getting-started demo).the source code is below：

#include <cstdio>
int main()
{
    printf("hello from ConsoleApplication10!\n");
    return 0;
}
after starting the debug,it shows a message：exception of type  "Microsoft.Build.Linux.Shared.ExceptionTTY" was thrown

![20180407130802](https://user-images.githubusercontent.com/12382259/38451728-beae0f98-3a67-11e8-9cb9-90f36525e481.png)

os version：win10 64it 1709 16299.309
vs2017 version： enterprise 15.6.5
linux version: Red Hat Enterprise Linux Server release 6.5 (Santiago) 64bit
gcc version:6.1.0
gdb version: 7.2-60.el6_4.1
gdb-server version:7.2-60.el6_4.1

**Comment by lukka** [comment] 2018-04-10 19:05
@leonheuler @GenKnight this problem should be already fixed in [Visual Studio 2017 15.7 Preview](https://www.visualstudio.com/vs/preview/).

Could you please try it out?

**Comment by lukka** [comment] 2018-04-10 23:12
FYI @leonheuler @GenKnight I just tried last build of VS 2017 15.7 Preview with RedHatEnterprise 6.7 and it worked.

![image](https://user-images.githubusercontent.com/681992/38588274-dd96bc24-3cd9-11e8-8327-355446d2960b.png)

The warning emitted by gdb is harmless, nevertheless we are going to address it, disregard that for the time being.

**Comment by GenKnight** [comment] 2018-04-11 08:40
Thanks a lot

**Comment by GenKnight** [comment] 2018-04-11 08:41
@lukka  Thanks a lot

**Comment by leonheuler** [comment] 2018-04-11 09:08
Didn't help. But now I have this in my new menu Cross Platform | Connection Manager | Remote Headers.. 
![image](https://user-images.githubusercontent.com/38251796/38607230-bde85020-3d80-11e8-8ee5-a1cec76a3519.png)
Btw sources are updoaded and compiled on the remote properly. I can execute it manually through terminal.

**Comment by lukka** [comment] 2018-04-11 17:44
@leonheuler are you still getting the ExceptionTTY when strating debugging with VS 2017 15.7 Preview? 
Could you please run on the remote the command 'tty' and look for the output.

**Comment by leonheuler** [comment] 2018-04-11 18:12
@lukka 
"are you still getting the ExceptionTTY when strating debugging with VS 2017 15.7 Preview?"
Yep. 
![image](https://user-images.githubusercontent.com/38251796/38635111-07f5956e-3dcd-11e8-92fb-911f6ccae46c.png)

**Comment by lukka** [comment] 2018-04-11 19:01
@leonheuler ok, thanks for the further info. 
As a workaround I would suggest to try another user instead of root, nevertheless the root cause need to be still understood here: could you please run this command and report the output?
```echo 'E2E32F1A-3E99-4EDF-A62A-10EDB5F81201'; tty; echo 'E4E32F1A-3E99-4EDF-A62A-10EDB5F81201' ```

**Comment by leonheuler** [comment] 2018-04-11 22:06
![image](https://user-images.githubusercontent.com/38251796/38645523-fb65ff1c-3dec-11e8-94a9-7f85cbb33aa8.png)

Ok I noticed one thing. If I enable UseDNS (as it was by default) in my /etc/ssh/sshd_config connection starts taking about 15 seconds and VS tells me:

1>------ Build started: Project: try, Configuration: Debug x86 ------
1>Validating architecture
1>Validating sources
1>Copying sources remotely to '192.168.0.102'
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(133,5): error : Could not connect to the remote system. Please verify your connection settings, and that your machine is on the network and reachable.
1>Done building project "try.vcxproj" -- FAILED.

**Comment by itodirel** [comment] 2018-04-11 23:17
@leonheuler that's caused by "zip", you will need to install it using apt

**Comment by VladimirR46** [comment] 2018-04-12 12:45
Hey. I have the same problem.
host:
os version：win7 64it Version 6.1.7601 Service Pack 1
vs2017 version： Visual Studio Professional 2017 15.7.0 Preview 3.0

remote:
Linux version 3.8.7-yocto-standard (neck@flax) (gcc version 4.9.1 (GCC) )
gcc version:4.9.1
gdb version: 7.7.1
gdb-server version:7.7.1
tty (GNU coreutils) 8.22
![image](https://user-images.githubusercontent.com/38318731/38677774-ee28451e-3e67-11e8-9c6a-bc96b720d6b0.png)

If you select
![image](https://user-images.githubusercontent.com/38318731/38677856-229e8826-3e68-11e8-9fd6-1e856136bc2c.png)
Error:
![image](https://user-images.githubusercontent.com/38318731/38677931-55097b54-3e68-11e8-8195-9b971788086b.png)

If you select
![image](https://user-images.githubusercontent.com/38318731/38677956-696dfade-3e68-11e8-9421-ee3ae4f90a82.png)
Error:
![image](https://user-images.githubusercontent.com/38318731/38677986-82d1032c-3e68-11e8-8905-06b3adce726e.png)

**Comment by lukka** [comment] 2018-04-12 18:12
@leonheuler @VladimirR46 thanks for reporting additional data for keeping the investigation going forward. I am going to reproduce the behavior on an Intel Edison board, and i will keep you up to date.

As a workaround I would suggest to select 'gdbserver' mode under 'debugging mode' in the project properties, although gdbserver needs to be installed on the board; since gdbserver is much smaller than gdb, this should not be a problem, as you do not need both at the same time.

**Comment by leonheuler** [comment] 2018-04-13 11:16
@lukka gdbservrer is installed actually. 

![image](https://user-images.githubusercontent.com/38251796/38732007-403d1bc8-3f25-11e8-8ad5-21ad29e3b630.png)

**Comment by lukka** [comment] 2018-04-13 23:06
@leonheuler 'gdbserver' should just launch correctly because i see you have it into the $PATH environment variable. This is a differen problem though, if you can please create a new issue thanks.

**Comment by VladimirR46** [comment] 2018-04-16 10:09
gdbservrer is installed.
![image](https://user-images.githubusercontent.com/38318731/38803261-527a895c-4177-11e8-8b4b-0c9af7be8d6f.png)


/usr/bin...  ls
![image](https://user-images.githubusercontent.com/38318731/38803232-3a84ae4a-4177-11e8-9aa1-bf226591fa9f.png)

**Comment by lukka** [comment] 2018-04-18 01:15
@leonheuler @VladimirR46 thanks for the information provided.
I tested with Intel Edison:
 1. Linux edison 3.10.98-poky-edison+ #1 SMP PREEMPT Mon Jun 6 14:32:08 PDT 2016 i686 GNU/Linux 
 2. GNU gdbserver (GDB) 7.7.1
 3. GNU gdb (GDB) 7.7.1
 4. gcc (GCC) 4.9.1

and I could not reproduce nor the "ExceptionTTY" nor the "GDBServer cannot start" problem. 

I connected to the device by USB cable (i.e. Ethernet over USB) and using no wifi.

I need help, could you provide more data that could be useful to reproduce the issue and fix it?
Also, is it possbile for you to try a different version of the OS image you are using?

**Comment by leonheuler** [comment] 2018-04-18 14:14
@lukka Ok debugging works fine with this remote image: https://sourceforge.net/projects/galileodebian/files/SD%20card%20Image/galileo-1.2.img.gz/download
(After booting 
g++ (Debian 4.7.2-5) 4.7.2
and GNU gdbserver (GDB) 7.4.1-debian
were installed with apt-get).
B.t.w VS sees OS version: Debian(x86) instead of Unknown(x86).
![image](https://user-images.githubusercontent.com/38251796/38937456-ecb4e980-432b-11e8-95a7-9577d346ec84.png)

**Comment by leonheuler** [comment] 2018-04-20 10:25
@lukka but there is huge troubles with Debian on Intel Quark since it has documented LOCK instructuon bug. Yocto is prefered.

**Comment by lukka** [comment] 2018-04-20 18:48
@leonheuler ok, hence Debian is not properly working onto the Galileo board and you need Yocto. Since it worked on Intel Edison and Linux 3.10.98-poky-edison and I could not reproduce the bug, I cannot say the problem is going to be fixed. Nevertheless feel free to provide more informations that could help us spot the issue. 

Suggestion: would it be possible for you to build a newer Yocto image and flash it on the Galileo board?

**Comment by lukka** [comment] 2018-09-10 05:54
@PrecisionWaveRF I am really interested into understanding what is the root cause of this problem.  Unfortunately I have not been able to reproduce the problem at all. Could you please contact us at vcpplinux-support at microsoft to verify how could we setup an exact repro of this scenario, thanks!

**Comment by lukka** [comment] 2019-01-04 23:32
@pvanoppen2 in the next preview of VS 2019 (preview 2) the start of the debugger in gdb mode is more resilient to timing issue. We do not have a fix for the current release VS 2017. Please open a reqquest on [DevComm](https://developercommunity.visualstudio.com) to prioritize a possible backport.

**Comment by itodirel** [comment] 2019-01-15 09:08
Hi, if this is still a issue, please reopen, closing this in an effort to get our issue list down

**Closed** 2019-03-19 04:29 UTC
Labels: investigating, need repro
