### ISSUE TITLE
Slow download of binaries

### ISSUE THREAD

**Issue by dedmen** [Microsoft/VSLinux#38] opened 2016-09-06 22:04 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:
- A brief description
  Compiled binaries like .o or .out files are downloading very slowly from a remote server.
- Expected results
  Compiled files should download with close to full bandwidth.
- Actual results (with build output window contents if applicable)
  Download bandwidth of MSBuild.exe is hovering at about 50KB/s
- System info
  Server is a x64 Debian Jessie up-to-date hosted at OVH. My ping to it is about 60ms and bandwidth over sftp/ftp/http is my full home bandwidth (2.7 MB/s down).
- Steps required to reproduce the error
  Compile on a real remote server.
- Additional info

When compiling on my raspberry pi which is connected via 100mbit LAN i get over 400KB/s for compiled binaries but the raspberry build still isnt a good alternative for one because its a different arch but its also slow.
And i dont really understand why every .o file has to be downloaded as it seems its not needed anyway on clientside. In my case i also dont need the final executable on my machine.
In my debug build my .o files are 27MB and my final executable is 12MB. Which takes a ton of time to download.
Here is an example of a compile where i only changed two chars in one source file.
![NetLimiter](http://image.prntscr.com/image/d30808a088da4aae8b66b11a2255574e.png)

**Comment by stanthomas** [comment] 2016-09-07 10:44
The executable needs to be available locally for the debugger (in gdbserver mode anyway). But I agree about the object files. Presumably something with the right name and date stamp has to be on the Windows host for incremental build to work but it might be faster to create zero-length dummy files locally following a successful compilation.

As for your network performance, if it's running 10x faster on a locally attached system then the issue is clearly with the remote and the connection to it. You can't really compare the VCLinux link speed to what you are getting from heavily optimised web / ftp clients and servers. Something like the  [boost::asio ssl example](http://www.boost.org/doc/libs/1_61_0/doc/html/boost_asio/examples/cpp03_examples.html) might be a fairer test.

**Comment by dedmen** [comment] 2016-09-07 15:06
The project Im compiling is actually using a boost tcp server which has good throughput. Dont have any UDP packet loss to my server either. I didnt test boost ssl servers on that machine yet but i used Qt SSL servers before and also got full bandwidth.
I also dont need to debug mostly.. As often thats just showing me crashes in unknown areas anyway. But i still build debug builds because they are sometimes more verbose on errors on stderr.
So most of the time i dont actually need the executable for the debugger so it would be nice to be able to specify an exclusion list for downloads.

**Comment by stanthomas** [comment] 2016-09-08 09:57
Given that the executable and object files are copied back for a reason, I'd say that an option to not copy them would be a non-starter.

But you could use a makefile project. The object (.o) files aren't copied back 'cos VCLinux doesn't know about them. And you configure the build target in VCLinux so, given you don't want to debug the application, as the final step in your makefile you could create a dummy file, e.g. `echo ok > a.out`  with a dependency on the actual executable. Tell VCLinux that the build target is `a.out` and it'll copy just that 3 byte file.

**Comment by dedmen** [comment] 2016-09-08 16:03
It seems to be a debian jessie problem. I just setup my laptop over Gbit Lan with 9KB MTU and debian jessie. I also only get 60KB/s from that. Ping is about 0.4ms

**Comment by robotdad** [comment] 2016-09-23 18:01
@dedmen just catching up on this one, I'm not seeing anything here for us to do. #51 was recently filed specifically on not copying back the .o files. Shall we close this one since the underlying issue was Jessie?

**Comment by dedmen** [comment] 2016-09-23 18:05
The root of the problem is not transmitting the .o files. Its the slow download on Jessie. not transmitting .o files would just make it a little better. But still something is capping download speeds when compiling on a Jessie Server. So there has to be some other issue. I don't think its as Jessie issue.. As file downloads via SFTP (which i think VSLinux is using according to connection to port 22) are using fullspeed.

**Comment by itodirel** [comment] 2016-11-16 03:51
I will investigate

**Comment by itodirel** [comment] 2016-11-19 02:50
I have not investigated the performance observations, but in 1.0.6, copying back object files is disabled by default. (You can enable it back if you want) And the link output copying can also be disabled if wanted, it's available in the Property Pages.

**Comment by dedmen** [comment] 2016-11-19 12:43
with "link output copying" You mean the final executable? Nice thanks. Good luck hunting that download speed problem.

**Comment by dedmen** [comment] 2016-12-22 10:18
#51 increased build time to 02:38 for a release build of my project.
60KB/s limitation is still there for the final binary though.

**Comment by dedmen** [comment] 2016-12-22 10:22
#51 increased build time to 02:38 for a release build of my project.
60KB/s limitation is still there for the final binary though.
Build time is 1:24 when disabling Linker output. So about 1 Minute download for a 3.4MB file.
I solved that by disabling download of linker output and instead using a post-build step that fetches it over sftp with full speed.

**Comment by itodirel** [comment] 2016-12-23 06:41
Thank you, and it's great to hear that you were able to workaround it. You should not need to. I found out what the problem was, and with the fix, it's comparable to other SFTP clients. The fix for this will be available in the next release.

**Comment by dedmen** [comment] 2016-12-23 18:41
Mind telling me what it was? ;)

**Comment by itodirel** [comment] 2016-12-23 22:43
it's the size of the internal buffers

**Comment by itodirel** [comment] 2016-12-23 23:45
just to give some numbers, a 4MB file used to take almost 1 minute, now it takes around 1 second, and a 100M file takes about 10 seconds

**Comment by dedmen** [comment] 2016-12-24 00:07
That would roughly be a build time increase from 2.5 minutes down to about 20 seconds between 1.0.5 and 1.0.7. I'm hyped already.

**Closed** 2017-06-19 22:05 UTC
Labels: bug, discussion, fixed
