### ISSUE TITLE
Intellisense doesn't work as expected in Visual Studio Linux Makefile project

### ISSUE THREAD

**Issue by AliAskari** [microsoft/VSLinux#332] opened 2018-09-12 14:33 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description

I have the following issues with my Visual Studio Linux Makefile projects:

- I don't see any database in my project/solution folder:
As far as I know Visual Studio should generate a database, a `.vs` folder, and store the intellisesne related information in a database but I cannot find anything other than the .sln/.vcxproj files in my solution/project folders.

- Intellisense works, and then decides not to work:
I get the squiggly red line under some variables and when I right click and select "Peek Definition" it goes away; and then comes back. Sometimes it goes away for good, but then again it returns after an hour. Very weird.

- The Linux headers/types are not found
There are a some types defined in Linux headers that the project cannot find, like: the `__builtin_ia32_pabsb128` and the family, `__float128`, etc.

I don't have these problems when I use the open folder CMake visual studio project, however the open folder is missing some big features that I cannot still use it.

* Expected results

Intellisense should be more consistent. 

* Actual results (with build output window contents if applicable)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

N/A

* Steps required to reproduce the error

Manually create a new VS Linux project or use this [repo](https://github.com/robotdad/vclinux) to create one for you and then try to use intellisense. 

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by itodirel** [comment] 2019-03-21 05:43
I see a .vs folder created.

For IntelliSense flakiness, can you enable IntelliSense logging from Tools - Options - Text Editor - C/C++ - Advanced - Diagnostic Logging, set Logging to True, and Logging Filter to 8, restart VS, logging will be in Output Window. Reproduce the bug, then please provide us with the log.

**Comment by itodirel** [comment] 2020-03-20 20:46
Tracked with: https://developercommunity.visualstudio.com/content/problem/484237/wsl-float128-is-undefined.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-20 20:46 UTC
Labels: investigating
