### ISSUE TITLE
False-positive on successful build

### ISSUE THREAD

**Issue by Stardidi** [Microsoft/VSLinux#168] opened 2017-08-07 14:28 UTC
When compiling my project using VS for Linux, it reports a successful build. However, checking the folder on my remote machine, no executable was produced. Running the actual linker command on that machine also produces an error that VS does not show.

My actual solution configuration is wrong, in that the library file is missing, so I would expect compilation to fail, and it does. However, VS reports incorrectly that it succeeded.

 VS2017 Community (26430.16) with Visual C++ for Linux 1.0.6, building to Ubuntu 16.04.2 LTS (GNU/Linux 4.10.0-30-generic x86_64)
gcc version 5.4.0 20160609

VS Build output:

_1>------ Build started: Project: master_server_linux, Configuration: Release x64 ------
1>Validating architecture
1>Validating sources
1>Copying sources remotely to -removed-
1>Starting remote build
1>Compiling sources:
1>Linking objects
========== Build: 1 succeeded, 0 failed, 13 up-to-date, 0 skipped ==========_

direct linking output:

_/usr/bin/ld: cannot find -llib/release/raknet/RakNetLibStatic.lib
collect2: error: ld returned 1 exit status_

**Comment by robotdad** [comment] 2017-08-16 20:28
@itodirel do you have a repro you can use to dig into this, or already understand the root cause?

**Comment by itodirel** [comment] 2018-11-28 22:01
@Stardidi Hi, is this still a problem? is there a repro we can use?

**Comment by itodirel** [comment] 2018-12-11 00:41
I'm not able to reproduce so closing, if it's still an issue please feel free to reopen

**Closed by itodirel** 2018-12-11 00:41 UTC
Labels: bug, need repro

**Comment by Stardidi** [comment] 2018-12-11 08:46
Unfortunately the setup I had is no longer available, nor am I working on this at the moment, so I cannot provide a repro. 

However, because of I'm currently not using VSLinux it's also not a problem for me anymore.
