### ISSUE TITLE
Visual Studio team absent from VSLinux for 2 months 

### ISSUE THREAD

**Issue by braindeaddeveloper** [Microsoft/VSLinux#169] opened 2017-08-07 15:38 UTC
Is there any one there listening to us ? 
No one appears to have responded in nearly 2 months.
Please confirm we aren't all wasting our time.

ever hopeful but somewhat doubtful

**Comment by stanthomas** [comment] 2017-08-08 13:46
A bit mean; I think 6 weeks would be a fairer estimate. But I'd agree, feedback from the VCLinux team is in short supply. I don't know if it's the same people but the VS group does seem to be dipping their toe in all sorts of waters, MinGW and Cygwin anyone?, and perhaps spreading themselves a little too thinly. There was a suggestion that VCLinux might be open-sourced. That would be an interesting strategy.

All said and done though, VCLinux works. Some shortcomings for sure, but no way am I going back to Eclipse.

**Comment by braindeaddeveloper** [comment] 2017-08-08 14:24
I was working from the basis of the last comment which was a question from robotdad on 14th June which yesterday was 54 days on ... so that's 7.714 weeks ... 2 months would have been 6 days more so you are correct I was 0.857 weeks out.  I stand corrected ... thanks Stan ! ... :-)

**Comment by braindeaddeveloper** [comment] 2017-08-08 14:33
I wish you were correct but there are some major issues that prevent it being used in an "industrial" environment which aren't being attended to or the user base being kept informed of the progress .. one I can think of has been an issue for over a year the last comment from ito being this is major I must fix it .........
Command lines (project properties c++ command line) aren't being correctly passed to gcc and include paths aren't being passed correctly either ... these are major things that need to be fixed URGENTLY for it to be a usable tool.  One minute my builds run the next they fail and they fail in different ways i.e. systemically not code failures ... if you build a remote project in situ and turn copying off and do a clean then ALL and I mean ALL of your files are permanently deleted from your remote location.  Only the fact that we have hourly daily weekly snapshots of our Linux file system saves us.  
And so on .. .
VSLinux .: Pull your finger our and fix these URGENTLY or your users will leak and not come back ... I have spent months trying to get a corporate build working but cant even get a small 4 project solution to reliably build and run ... look at this forum and get on with it ... PLEASE

many thanks

**Comment by itodirel** [comment] 2017-08-09 23:53
Sorry about that, we had some people in vacation and some of us were busy landing another (exciting) feature pertaining to Linux. We are getting on top of it, and won't let issues getting out of hand nor stale.

Regarding "_Command lines (project properties c++ command line) aren't being correctly passed to gcc and include paths aren't being passed correctly either_", I looked for a issue for this, but I could not find it, can you point to the issue number, crate a issue, or just explain it here?

Regarding "_if you build a remote project in situ and turn copying off and do a clean then ALL and I mean ALL of your files are permanently deleted from your remote location._", we fixed this bug.

Regarding "_One minute my builds run the next they fail and they fail in different ways i.e. systemically not code failures_", would you be interested to work with us and get to the bottom of that? We cannot reproduce it.

Regarding "_Command lines (project properties c++ command line) aren't being correctly passed to gcc and include paths aren't being passed correctly either ..._ ", can you provide us with a repro or log an issue on it?

**Comment by braindeaddeveloper** [comment] 2017-08-10 08:55
example includes not being forwarded from VSL to GCC

from proj / props / c/c++ / command line

"/path to gcc/gcc" -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-pointer-sign" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -std=c++11 -Wall -fno-strict-aliasing -I "/path to gcc/gcc/include/c++/4.8.3" -I "/path to curl/curl/include/" -I "/path to boos/boost/1_57_0/include" -g2 -gdwarf-2 "/path to gcc/bin/g++" -O0 "3600000" -fthreadsafe-statics -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -Werror -frtti -fno-omit-frame-pointer -std=c11 -fexceptions -o "\\path to project\teatest001\obj\x64\Debugx64\%(filename).o" 


from build output window 

...
    Invoking g++
/path to gcc/bin/g++ -c -x c++ /path to project/teatest001/main.cpp -I "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Linux\include\\usr\local\include" -g2 -gdwarf-2 -o "/path to project/teatest001/obj/x64/Debug/main.o" -Wall -Werror -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11 main.cpp

then I get include file not found errors as you can see includes from the command line window arent being passed to gcc 

unfortunately I cant send you more than this ... its a financial institution and a corporate offence to disclose anything more than this 

thanks

**Comment by braindeaddeveloper** [comment] 2017-08-10 08:56
Sorry ... will log an issue on this last

**Comment by braindeaddeveloper** [comment] 2017-08-10 09:00
Hey I forgot to say guy(s) ... welcome back !!! :-)

**Comment by robotdad** [comment] 2017-08-16 20:27
As Ion mentioned there's been a ton of activity that hasn't surfaced yet. That combined with summer vacations isn't a great excuse, but it's the truth. It's also true that we shouldn't have been as absent as we have. We're working to rectify that so you'll be seeing more of us around here.

**Comment by OtherCrashOverride** [comment] 2017-08-29 23:35
The obvious solution is to open source the project instead of providing an "issues only" repo.  When there is no timely response to issues and developers can not "help themselves" with source code, the only remaining option is to find an alternative.

I reported #141 in May.  At the time of this writing its now the end of August (3 months).  The lack of network support and lack of AArch64 support led me to conclude this is a "toy" initiative.  It becomes increasingly impossible to use Visual Studio for anything other than "messing around".  I need "big boy" tools for "big boy" development.  The cadence of Visual Studio is eclipsed (pun not intended) by that of technology.

This comment is meant as constructive criticism.  It is not intended to be a personal attack on any person or entity.  I hope that someday Visual Studio is useful as more than a text editor that has issue with line endings (but that is a bug report for elsewhere).

**Comment by braindeaddeveloper** [comment] 2017-09-07 09:23
You guys closed #170 when it wasn't fixed due to inactivity ? Are you serious ? I agree with the above comment in that case.  If you guys are serious about this product then you need to show us.  Closing an issue because of inactivity is doing that.  I have now spent a LOT of company time trying to get this to work when really I should be discarding an unsuitable tool and spending the time on projects.  The only reason I haven't is in the hope that it will pay future dividends.

**Comment by itodirel** [comment] 2017-09-07 16:47
@braindeaddeveloper, reactivated #170, thank you for the additional information, added some notes to #170; the reason we closed #170 was because it's something that we cannot reproduce on our ends, without more information there is nothing we could've done about it, so it wasn't a matter of closing a bug that we know it isn't fixed. Thank you for adding the additional information to #170, we will investigate.

**Comment by itodirel** [comment] 2017-09-07 16:49
@OtherCrashOverride, we have plans to open source the extension, thanks for the feedback.

Regarding #141, we are investigating

**Comment by AliAskari** [comment] 2017-09-08 01:07
@OtherCrashOverride 

> The cadence of Visual Studio is eclipsed (pun not intended) by that of technology.

This was epic. 

@itodirel @robotdad 
In my experience your team is one of the few teams at Microsoft who cares about the users but it could get much better. Open sourcing the product would certainly help every one and the issues would get resolved in a more timely manner. Nevertheless, thank you for the support.

**Comment by braindeaddeveloper** [comment] 2017-09-20 10:28
agree !

**Closed** 2017-10-24 21:18 UTC
Labels: discussion, investigating
