### ISSUE TITLE
Include paths not being passed from VSLinux to remote build

### ISSUE THREAD

**Issue by braindeaddeveloper** [Microsoft/VSLinux#170] opened 2017-08-11 09:19 UTC
I am getting repeated failures to find include files in various VSLinux projects.  

An example of this :

From project / properties / c/c++ / command line

"/path to gcc/gcc" -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-pointer-sign" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -std=c++11 -Wall -fno-strict-aliasing -I "/path to gcc/gcc/include/c++/4.8.3" -I "/path to curl/curl/include/" -I "/path to boos/boost/1_57_0/include" -g2 -gdwarf-2 "/path to gcc/bin/g++" -O0 "3600000" -fthreadsafe-statics -W"switch" -W"no-deprecated-declarations" -W"empty-body" -W"conversion" -W"return-type" -W"parentheses" -W"no-format" -W"uninitialized" -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -Werror -frtti -fno-omit-frame-pointer -std=c11 -fexceptions -o "\path to project\teatest001\obj\x64\Debugx64%(filename).o"

But when build is selected I can see from build output window

...
 Invoking g++
 /path to gcc/bin/g++ -c -x c++ /path to project/teatest001/main.cpp -I "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Linux\include\usr\local\include" -g2 -gdwarf-2 -o "/path to project/teatest001/obj/x64/Debug/main.o" -Wall -Werror -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11 main.cpp

then I get include file not found errors as you can see includes from the command line window arent being passed to gcc

As this is a remote build on a Linux machine :  -I "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Linux\include\usr\local\include" is pointless but as you can see that is the only include path passed to the remote build.

unfortunately I cant send you more than this ... its a financial institution and a corporate offence to disclose anything more than this

Repro is simple create  a VSLinux project against a remote Linux server over ssh add a remote include path to the settings run build then check the outputs command line.  Add a source file which has a #include "remoteheader.h" from that include path.  Run build and see error.

VS2017 is latest 15.2 version build 26430.16.  Remote server Redhat 6.5 GCC version 4.8.3

thanks

**Comment by itodirel** [comment] 2017-08-21 23:54
@braindeaddeveloper 

Regarding the Command Line observation, I want to note that what you see in the Property Pages in the Command Line section, it's an approximation of the actually command line, the reason for that being extra code that we run only during the build and the Property Pages doesn't have access to. For the most part, the discrepancy will only be duplicates and de-duplication. 

Regarding additional include directories. The way you can add the is using Property Pages - Configuration Properties - C/C++ - General - Additional Include Directories. This is a semi colon separated list, of both local and remote paths. The local paths are only used for IntelliSense, the remote paths are only used for build.

So if you wanted to add a directory say /usr/src/linux-headers-4.8.0-41/usr, the you can just append that to Additional Include Directories, and reference it with #include <> syntax, note that in C++, quotes in #include only resolves files relative to the directory in which the source file the #include is made from, while #include <foo.h> for example, is resolving the header using the Additional Include Directories.

Please let me know if this doesn't work for you or you have more questions.

**Comment by braindeaddeveloper** [comment] 2017-08-23 13:46
Wow ... Ion ... I have been using VS since the early 90's from 1.52 and on NT 3.51 ... the above is like what you suggest to an intern or graduate.  If you are saying what appears in the properties -> Configuration -> C++ -> Command Line has no direct relationship to the Command Line actually used (ignoring uniqueness and ordering) then I am worried .... to be precise ... my 
-I some path 
entries in the above property page do NOT appear in the executed command line and so fail to compile ... I cut and pasted a full example above ... you are ignoring the -I entries there when you say I should be using the Additional Include Directories ... they are there ! look ! above ! in the Command Line page ... but NOT in the executed command line.
If I cut and paste the executed command line into a text editor and add the -I entries ... the compilation is successful.  
Not really sure how much more explicit I can be ...

many thanks

**Comment by itodirel** [comment] 2017-08-24 22:55
@braindeaddeveloper, apologies, I'm just trying to cover all the bases. Can you verify one more thing, when you modify the values in Property Pages, is the Active Configuration and Platform selected? In the Property Pages it should say "Active" at the top. Sometimes the configuration or platform can switch from the Active one, so if you add any settings it will effectively not be applied to build if it is not set in the active one.

**Comment by braindeaddeveloper** [comment] 2017-08-25 09:08
Hi Ion
Yes ... the active configuration has the include paths set in property pages but the command line executed doesn't.  
BTW As I was aware the Active indication is only a reference to the underlying configuration.  So Active(XYZ) points to XYZ. So its XYZ that is the configuration and you can modify those without them being active as in All Configurations or Multiple Configurations.

I have to say this is a killer.  thanks

**Comment by itodirel** [comment] 2017-08-26 00:34
Is `-I "/path to curl/curl/include/"` specifically, exactly what you're adding to the Configuration Properties - C/C++ - Command Line? I'm not able to reproduce it on 15.2, on the exact same build that you're using (26430.16). Can you try reproducing outside your project, with a simple (new) Console Application project, and see if it's specific with the project that you're using or there is something else going on? So we can further diagnose it and narrow it down. If you're able to reproduce with a Console Application project, then would it be possible to give us the build logs in diagnostic verbosity?

Additionally, I attached a project that I used in some of my testing of this issue, would it be possible to open it and try to build it and see if you can see the -I include or not included?

[ConsoleApplication1.zip](https://github.com/Microsoft/VSLinux/files/1253280/ConsoleApplication1.zip)

**Comment by itodirel** [comment] 2017-09-05 22:47
Tentatively closing due to inactivity. If this still reproduces for you, please reactivate and provide us with the repro steps.

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:11
Hi Ion
I cannot use VSLinux anymore due to this ... none of my projects (and I have upgraded to 15.3) pass ANY include file paths to the remote build apart from the pointless path to the windows folders : -I "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\Linux\include\usr\local\include" 

I cannot send any more than I have without risking being expelled from the company as it is a corporate offence to send code of any sort out of the company and there are detectors running ... it is an investment bank.  

 -I "/<path to curl>/curl/include/" 

is certainly not what I am passing ... I have just remove the <path to curl> with a place holder

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:12
I don't think it right you closed this ....

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:16
Hi Ion

added comments I cannot reactivate please do so as I cannot use VSLinux at all and the same with 15.3

thanks


regardz
mark

On 5 Sep 2017, at 23:47, Ion Todirel <notifications@github.com<mailto:notifications@github.com>> wrote:


Tentatively closing due to inactivity. If this still reproduces for you, please reactivate and provide us with the repro steps.

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:32
I get the following when I try and open the project in 15.3:
=====================
06/09/2017 11:21:18
LimitedFunctionality
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Linux.Shared.RemoteTargetUtils.ProcessorArchToPlatform(String remoteArchitecture)
   at Microsoft.Build.Linux.Shared.RemoteTargetUtils.ConnectionToDisplayNameShort(StoredConnectionInfo storedConnectionInfo)
   at Microsoft.VisualStudio.Linux.ProjectSystem.v2.LinuxRemoteDebugTargetsProvider.<GetEnumeratorEnumValuesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Linux.ProjectSystem.v2.LinuxRemoteDebugTargetsProvider.<>c__DisplayClass25_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
---> (Inner Exception #0) System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Build.Linux.Shared.RemoteTargetUtils.ProcessorArchToPlatform(String remoteArchitecture)
   at Microsoft.Build.Linux.Shared.RemoteTargetUtils.ConnectionToDisplayNameShort(StoredConnectionInfo storedConnectionInfo)
   at Microsoft.VisualStudio.Linux.ProjectSystem.v2.LinuxRemoteDebugTargetsProvider.<GetEnumeratorEnumValuesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Linux.ProjectSystem.v2.LinuxRemoteDebugTargetsProvider.<>c__DisplayClass25_0.<<Initialize>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)<---

===================

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:39
I would note that I can see in project properties c/c++ all options : Additional Options : -I /usr/include
BUT in 
project properties c/c++ command line : the -I /usr/include is missing

**Comment by braindeaddeveloper** [comment] 2017-09-06 10:43
I can confirm that -I /includepath into Additional Options :
project->properties->c/c++->all options : Additional Options : -I /usr/include
works and the -I ... is added to the remote command line

**Comment by itodirel** [comment] 2017-09-07 16:26
Reactivating based on activity

**Comment by itodirel** [comment] 2017-09-19 21:15
@braindeaddeveloper regarding the exception that your seeing, could you open a separate issue for that? some questions about it, what is the version of Visual Studio that you are using? I'm looking for the entire version number from Help - About.

**Comment by braindeaddeveloper** [comment] 2017-09-20 09:46
Hi Ion
Microsoft Visual Studio Professional 2017 
Version 15.3.3
VisualStudio.15.Release/15.3.3+26730.12
Microsoft .NET Framework
Version 4.6.01055

Installed Version: Professional

Visual Basic 2017   00370-10000-02467-AA085
Microsoft Visual Basic 2017

Visual C# 2017   00370-10000-02467-AA085
Microsoft Visual C# 2017

Visual C++ 2017   00370-10000-02467-AA085
Microsoft Visual C++ 2017

Visual F# 4.1   00370-10000-02467-AA085
Microsoft Visual F# 4.1

Application Insights Tools for Visual Studio Package   8.8.00712.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2017   15.0.30726.0
ASP.NET and Web Tools 2017

ASP.NET Core Razor Language Services   1.0
Provides languages services for ASP.NET Core Razor.

ASP.NET Template Engine 2017   15.0.30726.0
ASP.NET Template Engine 2017

ASP.NET Web Frameworks and Tools 2017   5.2.50601.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v3.0.0   15.0.30728.0
Azure App Service Tools v3.0.0

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GitHub.VisualStudio   2.3.2.32
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

JavaScript UWP Project System   2.0
JavaScript UWP Project System

MenuCommands Extension   1.0
MenuCommands Visual Studio Extension Detailed Info

Microsoft Continuous Delivery Tools for Visual Studio   0.3
Simplifying the configuration of continuous build integration and continuous build delivery from within the Visual Studio IDE.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

Node.js Tools   1.0.0.0
Adds support for developing and debugging Node.js apps in Visual Studio

NuGet Package Manager   4.3.1
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

SQL Server Data Tools   15.1.61707.200
Microsoft SQL Server Data Tools

TypeScript   2.3.4.0
TypeScript tools for Visual Studio

Visual C++ for Linux Development   1.0.7
Visual C++ for Linux Development

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio tools for CMake   1.0
Visual Studio tools for CMake

Visual Studio Tools for Universal Windows Apps   15.0.26730.08
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Extension Pack 2017   15.0.2
The easiest way to set up Visual Studio for the ultimate web development experience.

**Comment by braindeaddeveloper** [comment] 2017-09-20 09:47
I can confirm there are no funny characters in the server name other than dots i.e.
server.domain.ext in this case:
abcd1234.company.com

**Comment by braindeaddeveloper** [comment] 2017-09-20 09:48
Also I am not seeing an exception ... 
I am not seeing the include paths :-)

**Comment by itodirel** [comment] 2017-10-09 23:04
@braindeaddeveloper could you open a separate issue for the  System.NullReferenceException exception?

**Comment by ademyankov** [comment] 2017-10-13 17:52
I am seeing the same problem. Adding **_-I "$(RemoteProjectDir)/include"_** into _C/C++->Additional Options_ doesn't do anything, and the build fails!

**Comment by itodirel** [comment] 2017-11-09 01:27
@ademyankov regarding the relative path problem, that is a known bug and we are planning on fixing it soon @braindeaddeveloper is that the same problem you're seeing?

**Comment by braindeaddeveloper** [comment] 2017-11-09 11:04
@itodirel, @ademyankov ... no I was specifying full paths

**Comment by virooo7** [comment] 2017-12-28 03:22
I am facing the same problem with VS2015, replacing the relative path with the whole path seems to solve the problem as @ademyankov suggested.

**Comment by braindeaddeveloper** [comment] 2017-12-28 10:14
I have updated to 15.5 and started a new project against a new linux host and its still happening ... doesnt matter how I add the additional include paths they arent passed over to the compiler on linux unless I specifically add them to the Additional Options field of the C/C++->Command Line property page.
I would note that they are identically specified/shown in the All Options read only field of the same page so they are understood by VS ... just not sent to the linux compiler. Also in 2017 15.5 I can now see a strange xml tag : <different options> being shown in both the C/C++ and Linker pages of the same name (Command Line) except in the Linker one there is nothing but this tag.

gcc compiler : 4.83
linux host : Redhat 6.5
windows host : Windows 7

**Comment by braindeaddeveloper** [comment] 2017-12-28 10:16
So I have a question : is there a documented or undocumented flag I can use with VS or in the solution/project settings to show exactly what is being sent to the remote linux host ? Unfortunately I dont have the ability/rights to use netmon or any packet sniffers as its an investment bank and very tightly regulated.

**Comment by itodirel** [comment] 2018-01-03 02:43
We will need a repro, or if you like you can contact us directly at vcpplinux-support@microsoft.com. I would recommend trying to get a small repro that doesn't involve any of your IP and once you can repro, share the repro with us: logs and the project. 

Yes. Please change the verbosity in Tools - Options - Projects and Solutions - Build and Run - MSBuild project build output verbosity, to Normal. And then when you build, you will see the compiler command line as this, in the Output Window:

```
1>  Invoking 'g++'
1>  g++ -c -x c++ /home/iontodirel/projects/ConsoleApplication6/main.cpp -g2 -gdwarf-2 -o "/home/iontodirel/projects/ConsoleApplication6/obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
```

If you add an additional include, in Property Pages - Configuration Properties - C/C++ - General - Additional Include Directories, it will show up like this:

```
1>  Invoking 'g++'
1>  g++ -c -x c++ /home/iontodirel/projects/ConsoleApplication6/main.cpp -I /home/foo -g2 -gdwarf-2 -o "/home/iontodirel/projects/ConsoleApplication6/obj/x64/Debug/main.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c++11
```

Note that currently the paths specified there, have to be absolute, remote paths, not local, nor Windows ones. The path above I added is /home/foo, notice the -I just after main.cpp above.

**Comment by itodirel** [comment] 2018-01-18 22:52
@braindeaddeveloper I created this video as a demo for this, would it be possible to take a look and tell us where it breaks?

**Comment by braindeaddeveloper** [comment] 2018-01-19 14:44
Hi Ion ... I'm afraid that's blocked from work I will check when I get home.  thanks

**Comment by itodirel** [comment] 2018-01-26 22:23
Hi @braindeaddeveloper did you have any success in configuring your includes?

**Comment by sraboy** [comment] 2018-02-04 23:14
This is still an issue with relative includes on VS2017 15.5.6, with WSL as my build target. While the include files themselves are copied remotely and placed in their directories according to the project filters, the fact that the directories are referenced as "Additional Include Directories" appears to only affect Intellisense recognition and I'm required to update my sources to reference each include file by relative directory.

Unsure if it's related, but there appear to be issues with directories with Linux projects in general. I also had to fiddle with the remote output and debugging directories to get things to show up in the expected place. Part of the issue was that I was trying output files to `$(ProjectDir)build\$(Platform)-$(Configuration)\` but that `-` was getting translated to a `/` so I had to change it to `_` and part of it seems related to the fact that I use `$(SolutionDir)` in several places, which is one dir above the project, and causes some files to be copied improperly.

I eventually got things to properly copy remotely and launch GDB, though when the 
compiled object files are copied back to my system (based on Linker settings), my hack of using `..` in the remote path causes all the `obj` files to also be placed at `..` relative to the expected location.

You can attempt to reproduce with the solution [in this repo](https://github.com/sraboy/rapidtest) by building/launching the `rapidtestlinux` project.

**Comment by svenbieg** [comment] 2018-02-11 17:02
An additional include directory doesn't work. You have to specify an additional compiler option "-Iprojects" and You Need to use angle brackets and slashes, **no** back-slashes! <Default/Platform.h> for example.

**Comment by vgoldring** [comment] 2018-03-10 20:54
I have exact same problem with the latest version of VS2017, use absolute paths, and tried reinstalling it several times, including full removal. VS passes to Linux WRONG include directories, only some etc.

**Comment by yuehuang010** [comment] 2018-03-15 02:42
Hi @vgoldring , I am looking at the issue.  In 15.7, we have revamped the translator between pc and linux.  Can you provide examples of paths that is not translated correctly?

Here are few cases where translation are skipped.
Absolution path to missing directories are not translated.  
Paths that start with '/' or '~/' are not translated.
Drive letters (C:) alone are ignored.   (C:\) is ok.

**Comment by vgoldring** [comment] 2018-03-15 15:36
Hi Felix,

 

Thank you for looking at the problem.

What do you mean by “not translated”? The problem is not “between pc and linux”, but in not sending some paths listed in the Additional Include Directories of General page for C/C++ in project settings. If by “not translated” you mean “not sent to Linux”, this would be bug, as additional include directories sent to g++ may not (and usually do not) exist on the PC, but only on the Linux machine. If that’s the case, noting that an absolute path on Linux begins with ‘/’ (the only kind supposedly supported now according to the tool’s blog, not relative), so how can you not “translate” and not send those?

 

From the behavior of the CLinux we can see that it’s not really true. Some paths are sent, and other are not.

In the example I uploaded (I will attach more here), all paths given as -I in Command Line Additional Options page when present in the Additional Include Directories (the location we all previously considered normal for configuration of the project and from where they were moved to Additional Options of Command Line) are not sent to g++. The others are still in the original place and are being sent fine. Moving those that were not sent to the Command Line’s Additional Options is our workaround.

 

Please find some projects attached, along with the solution.

 

Sincerely,

                Val Goldring

**Comment by vgoldring** [comment] 2018-03-15 15:45
On a separate note, why would even touch the part of the project that worked fine?

The project itself is not (and cannot be) represented on PC in full.

All of the environment is actually only on Linux machine.

The header files necessary for Intellisense (which may or may not be full set of headers used for compilation) works when indicated in VC++ Directories page Include Directories. This arrangement was simple enough and usable, if not clearly documented. People figured it out and used in their projects.

 

More ambitious approach of automatically supporting full set of headers for Intellisense is implemented by VisualGDB, but took a long time to bring to a reasonably working state and I believe is still prone to breakdowns, particularly when moving or accessing a project from different PCs or to compile on different Linux machines. It also undertakes large, sometimes huge downloads of whole directories (not just header files) and may be time consuming on some networks.

**Comment by yuehuang010** [comment] 2018-03-15 18:00
Hello @vgoldring , I can't determine what has changed from the details provided.  Could you please copy and paste the your Additional Option workaround and your input in Additional Include directories?

Until I know more, I can't provide detail on what regressed.  VC++ Linux is actively being developed and even with the best of testing, regression are still possible.  Preview time period allow us to take feedback and actively make fixes.

Once again.  Thanks you for use Preview builds.

**Comment by itodirel** [comment] 2018-04-03 01:03
@vgoldring @svenbieg @braindeaddeveloper can you give us a repro, we are unable to reproduce what you're seeing; @vgoldring the solution that you attached would not help us, we need the project, if you can't give us the project, please give us a minimal repro; can you also tell us exactly the version of Visual Studio that you're using? You can get it from help about;

If you follow this video, can you tell us what you're doing different? [Visual C++ for Linux Development - Setting up additional include directories](https://vimeo.com/251710903)

**Comment by itodirel** [comment] 2018-04-03 01:15
@vgoldring 

> More ambitious approach of automatically supporting full set of headers for Intellisense is implemented by VisualGDB, but took a long time to bring to a reasonably working state and I believe is still prone to breakdowns, particularly when moving or accessing a project from different PCs or to compile on different Linux machines. It also undertakes large, sometimes huge downloads of whole directories (not just header files) and may be time consuming on some networks.

**Comment by itodirel** [comment] 2018-04-03 01:15
@vgoldring 

More ambitious approach of automatically supporting full set of headers for Intellisense is implemented by VisualGDB, but took a long time to bring to a reasonably working state and I believe is still prone to breakdowns, particularly when moving or accessing a project from different PCs or to compile on different Linux machines. It also undertakes large, sometimes huge downloads of whole directories (not just header files) and may be time consuming on some networks.

**Comment by vgoldring** [comment] 2018-04-03 01:25
I did send you several project files along with the solution.

What I do differently that in the video is that I add additional include directories before the already predefined variables, not after as in the video. Also, I remove one or all of them as they introduce into the build path a useless directory from the PC.

**Comment by itodirel** [comment] 2018-04-03 01:34
We do not have the project attachments.

Can you gives us an example of an include path that is not passed to the compiler?

**Comment by itodirel** [comment] 2018-11-29 01:59
Hi, we are not able to reproduce, please let me know if there are any issues here, and I'd happily reactivate and look into it, we are trying to get the issue list number down, so tentatively closing

**Closed by itodirel** 2018-11-29 01:59 UTC
Labels: need repro

**Comment by svenbieg** [comment] 2018-12-25 18:46
You have to add "Iprojects/$(SolutionName)/$(ProjectName)" to the command line options. Then You can include files relative to the project-directory using brackets " and slashes /, no back-slashes. The solution-directory is not working, by the way.

**Comment by svenbieg** [comment] 2018-12-25 18:59
The command line option "-iquote projects/.." does work! But only with quotes " and slashes /!
