### ISSUE TITLE
Linux.targets(341,5): error : Packet is too big

### ISSUE THREAD

**Issue by jambagigirish** [Microsoft/VSLinux#316] opened 2018-07-26 19:25 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description-
Linking error of Packet is too big

* Expected results-
linking successful and project is built succesfully
* Actual results (with build output window contents if applicable)
Other small project build perfectly fine- But this project has 1600 source code files - Applications.vcxproj
C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Microsoft.CppBuild.targets(376,5): warning MSB8004: Intermediate Directory does not end with a trailing slash. This build instance will add the slash as it is required to allow proper evaluation of the Intermediate Directory.
1>Validating architecture
1>Starting remote build
1>Compiling sources:
1>Linking objects
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(341,5): error : Packet is too big. Maximum packet size is 68536 bytes.
1>Done building project "Applications.vcxproj" -- FAILED.

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual c++ for Linux development 1.0.9, 
gcc version -Remote_GCC_1_0 , Centos vm on Windows 10 versions. 

* Steps required to reproduce the error
build a project which has more than 1000 files 
* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by lukka** [comment] 2018-07-26 22:06
Duplicate of #314

**Closed by lukka** 2018-07-26 22:06 UTC

**Comment by itodirel** [comment] 2020-03-20 03:31
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
