### ISSUE TITLE
Build Dependencies/References in sollution not working as expected

### ISSUE THREAD

**Issue by j1and1** [microsoft/VSLinux#214] opened 2017-11-02 10:44 UTC
So I created a C++ static library project in VS and C++ application project for linux in the same solution. As my app is depending on my custom lib I added it as applications project Build Dependency as I normally do in VS C++ projects

**Expected result** -> Header search paths from my custom lib are automaticly added to my C++ App project and also libMyLib.a added to linker with my library search path

**Actual results** -> It does not happen automaticly resulting in build failed... and to make it work I have to manually add Header search paths and linker options

**Steps required to reproduce the error**

1. Create a new linux solution with static lib and executable
2. Add your lib to app executable as build dependency as you would normaly do in VS
3. try to compile it

If I am missing something or there is a workaround for this I really would like to know...
And also thanks for the great job of implementing this.....

**Comment by ademyankov** [comment] 2019-11-06 23:00
@j1and1 no you are not missing anything. I have the latest vs2019 and this crap is still there, and it doesn't work as expected. Total clusterfuck with Linux paths. I wish, at my job, I had the luxury of not following the customer's bug reports for 2 years, like this guy @itodirel I guess I have to join Microsoft in order to be able to do that.

**Comment by itodirel** [comment] 2020-03-25 07:27
This is a duplicate of #363, to answer your question @ademyankov, no, this scenario is not supported and we don't expect it to work, this is not a bug. It can be workarounded by specifying the inputs and search paths explicitly in Property Pages. We will evaluate a fix, we estimate this will not be expense, and track it as part of #363.

**Closed by itodirel** 2020-03-25 07:27 UTC
Labels: question
