### ISSUE TITLE
Inconsistent handling of Additional Include Directories

### ISSUE THREAD

**Issue by drrggibbs** [microsoft/VSLinux#240] opened 2017-12-29 19:54 UTC
VSLinux doesn't handle the "Additional Include Directories" property consistently. For example if I define it to be 
../../Library;../../Library/Linux
then for the g++ options this is converted to something like 
-I /home/user/projects/ProjectName/../../Library -I /home/user/projects/ProjectName/Linux 
i.e. the first is appended to the name of the Remote Build Project Directory, which is what I want, but the second has lost the ../.., which not what I want.

Shouldn't the first form be what always happens, i.e. just append the relative path to the remote path?

Using VS 2015 and VSLinux 1.0.7

**Comment by lukka** [comment] 2017-12-30 00:22
@drrggibbs Could you please retry your scenario with VS2017?

**Comment by drrggibbs** [comment] 2017-12-31 14:18
Tested with VS 2017 (15.5.2) and VC Linux 1.0.8.
Same behavior.

**Comment by yuehuang010** [comment] 2018-01-30 20:34
Hi, thank you for bring this to our attention.  I have fix an issue where ".." in paths wasn't combining correctly.  Part of the problem was when LocalProjectDir didn't end with a trailing slash, so the translator eat a folder.  I will let you know when the fix is in live.

**Comment by itodirel** [comment] 2019-01-18 09:08
this is a relative paths issue, same as #325

**Comment by itodirel** [comment] 2020-03-26 06:09
We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-26 06:09 UTC
Labels: closed, duplicate
