### ISSUE TITLE
Remote Makefile project builds, but will not debug if relative path "~/folder" is used

### ISSUE THREAD

**Issue by tawe141** [Microsoft/VSLinux#304] opened 2018-06-18 06:00 UTC
* A brief description
Similar to #99 although mine builds successfully. Previously, my project was compiling with g++ remotely, but after some troubles linking libraries, I use a cmake file on my remote server. VS is set up to run `cmake . && make` as its build command. I kept getting an error saying the remote output file could not be found, so out of frustration, I changed the root project directory to an absolute path, like `/home/username/projects`. This then works. 

* Expected results
Relative paths like `~/projects` should work just as well. 

* Actual results (with build output window contents if applicable)
No different build output, although interestingly the system still copies my output file to my local computer, meaning it can find it just fine. The debugger, however, could not find the file. 

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Visual Studio 15.7.3
CentOS 6.6
gcc 4.4.7
gdb 7.2
cmake 2.8.3

**Comment by lukka** [comment] 2018-06-18 18:05
@tawe141 we would strongly suggest to use the Open Folder / CMake functionality instead of using Makefile based vcxproj project. Just select Open Folder and select the directory that contains the root CMakeLists.txt file. Then in the CMakeSettings.json file set the remote hostname you want to run the build and debugging on. Let us know!

**Comment by itodirel** [comment] 2019-01-18 09:01
@tawe141 as Luca suggested, is that something you could use? for the relative paths issue, using #325 to track since it's the same underlying issue

**Comment by itodirel** [comment] 2019-03-19 04:31
closed as duplicate and using 325 for tracking

**Closed by itodirel** 2019-03-19 04:31 UTC
Labels: duplicate

**Comment by itodirel** [comment] 2020-03-20 03:37
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
