### ISSUE TITLE
cannot step into shared object library using gdbserver

### ISSUE THREAD

**Issue by SamuelHenderson** [Microsoft/VSLinux#319] opened 2018-07-31 16:42 UTC
* A brief description
I'm using gdbserver, because the remote linux machine I am connecting does not have gdb installed (it only has gdbserver).  
If I add a shared object library project to my solution and put some breakpoints in it's code and some breakpoints in the application I'm debugging... When I start debugging, the breakpoints in the application code are hit and I can step through application code no problem.  The breakpoint in my shared object code however are not hit.  They appear as empty breakpoints with the ! symbol on them.  Hovering over them I see the following tooltip message: 
`"The breakpoint will not currently be hit. Module containing this breakpoint has not yet been loaded or the breakpoint address could not be obtained."`.  
The debugger steps over the calls into the shared object code and my breakpoints in it are not hit.  The library compiles and links fine.  My application (which depends on the shared object library) is able to compile and link fine as well.

It's entirely possible that I am just missing something in Visual Studio to get it's local gdb client loading my shared object files.  I thought that's what the 'Additional Symbol Search Paths ('solib-search-path')' was for ...  At any rate, I'm attaching a simple sample project :)

* Expected results
The ability to debug shared object code with gdbserver the same way I can using gdb.

* Actual results (with build output window contents if applicable)
(Show output from: Debug)
`Loaded 'shared libraries loaded at this time.'. Cannot find or open the symbol file.
Stopped due to shared library event:
  Inferior loaded /home/lotsys/projects/Test/bin/x64/Debug/**libTest.so**
    /lib/libstdc++.so.6
    /lib/libm.so.6
    /lib/libgcc_s.so.1
    /lib/libc.so.6
    /lib/ld-linux-x86-64.so.2
Loaded '/home/lotsys/projects/Test/bin/x64/Debug/**libTest.so**'. Cannot find or open the symbol file.
Loaded '/lib/libstdc++.so.6'. Cannot find or open the symbol file.
Loaded '/lib/libm.so.6'. Cannot find or open the symbol file.
Loaded '/lib/libgcc_s.so.1'. Cannot find or open the symbol file.
Loaded '/lib/libc.so.6'. Cannot find or open the symbol file.
Loaded '/lib/ld-linux-x86-64.so.2'. Cannot find or open the symbol file.`

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. 
Visual Studio Enterprise 2017 Version 15.8.0 Preview 5.0
VC++ for Linux: 1.0.9.27294
Fedora 28
gdbserver 8.0

* Steps required to reproduce the error

1. Create a new solution and add two empty Visual C++ For Linux Projects.  

2. Make one an application (.out) project and make one a shared object (.so) project.  

3. Add code to each project.  Preferably, call code from the shared object project in the application project.  

4. Add the output of the shared object project as a Library Dependency of the application project. (Make sure to add the remote output directory of the shared object project as an Additional Library Directory for the application project).  
[termsim_hello_world.zip](https://github.com/Microsoft/VSLinux/files/2246243/termsim_hello_world.zip)

5. Make sure both projects build correctly on the linux system.  

6. Set the Debugging Mode for the application to be gdbserver

7. Set 'Additional Symbol Search Paths' ... is this supposed to be a windows path to the *.so library file on my local Windows system (C:\Users\me\Source\MyApp\Test\bin\x64\Debug\) or a linux path to the *.so file on the remote system (/home/lotsys/projects/Test/bin/x64/Debug) ?

* Required packages and commands to install
None that I know of ... aside from gdbserver :)

**Comment by paulmaybee** [comment] 2018-07-31 18:38
Looks like a bug in setting the solib-search-path. To work around it, instead of setting the "Additional Symbol Search Paths" property you can put the command:
`set solib-search-path C:/temp/termsim_hello_world/Test/bin/x64/Debug`
into the "Additional Debugger Commands" property. 
For breakpoints to bind correctly you will also need to point to your non-project source in the "Additional Sources File Path Map" property. In this case "non-project" means the "Test" code, since that is not the project you are launching. So set it to something like:
`C:\temp\termsim_hello_world\Test=/home/Iotsys/projects/Test`
With these two changes I was able to successfully debug your app.

**Comment by SamuelHenderson** [comment] 2018-07-31 20:47
Thanks paulmaybee!  This works 👍 .  However, my actual Visual Studio Solution I'm working with has 15 shared object library projects ... I guess I'll need to map each project path  for the Sources File Path Map.

**Comment by paulmaybee** [comment] 2018-07-31 20:52
I believe that if they are all under a common solution you can do something like:
C:\temp\mySolution=/home/Iotsys/projects

This will work as long as the source paths under "mySolution" on the windows machine matches the souce paths under "projects" on the linux side. Which they usually would for a normal solution.

**Comment by SamuelHenderson** [comment] 2018-08-01 13:26
Excellent.  Thank you very much again. 

 I guess the bug with 'Additional Symbol Search Paths' will be resolved in a future update?

**Comment by paulmaybee** [comment] 2018-09-18 17:33
Fixed in the next major release of VS

**Comment by itodirel** [comment] 2019-03-19 04:14
@SamuelHenderson please let us know if this problem is now gone for you, and reopen otherwise

**Closed by itodirel** 2019-03-19 04:14 UTC
Labels: bug understood, fixed

**Comment by itodirel** [comment] 2020-03-20 03:28
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
