### ISSUE TITLE
Cannot debug forked program

### ISSUE THREAD

**Issue by drrggibbs** [microsoft/VSLinux#239] opened 2017-12-29 18:51 UTC
I can't figure out if it's possible to debug the child of a forked process.

If Configuration Properties > Debugging > Debug Child Processes is set to No, then the child is not debugged.

If it's set to Yes, then the breakpoints are enabled in the child, but if one is hit the child terminates on a SIGTRAP. Setting "Additional Debugger Commands" to "set follow-fork-mode child" didn't help.

I also tried executing the program directly on the Linux machine, then while it was paused I tried attaching to the child from VS, but I get a dialog saying the debugger "was unable to automatically select an appropriate type of code".

Using VS 2015 and VSLinux 1.0.7

[main.cpp.txt](https://github.com/Microsoft/VSLinux/files/1593708/main.cpp.txt)

**Comment by drrggibbs** [comment] 2017-12-31 14:11
Reran with VS 2017 (15.5.2) and VC Linux 1.0.8

1. Running in gdbserver mode. Always get a SIGTRAP whether "Debug Child Process" is set "Yes" or "No".
2. Running in gdb mode with "Debug Child Process" set to "No" - breakpoints in the child are ignored.
3. Running in gdb mode with "Debug Child Process" set to "Yes" - breakpoints set at 11, 14, 30, & 33.
   Stops at 11 then 30. Press enter in the Linux Console to continue the child. Stops at 34.
   Pressing F5 continues to stop at 34. Output window displays - 
   
Program received signal SIGINT, Interrupt.
main () at /home/richard/software/ConsoleApplication2/main.cpp:34
34		printf("child: goodbye\n");

Thread 1 "ConsoleApplicat" received signal SIGINT, Interrupt.
0x00007ffff7ad907a in __GI___waitpid (pid=29387, stat_loc=0x7fffffffe990, options=0) at ../sysdeps/unix/sysv/linux/waitpid.c:29
29	in ../sysdeps/unix/sysv/linux/waitpid.c

4. Running in gdb mode with "Debug Child Process" set to "Yes" - breakpoints set at 11, 14, & 33.
   Stops at 11. After pressing F5 waits for child input. After pressing enter in the Linux Console, stops at 34, the same behavior as above.

5. Running in gdb mode with "Debug Child Process" set to "Yes" - breakpoints set at 11, 14, & 33 (same as 4)
   Stops at 11. Press enter in the Linux Console - output from line 33 is displayed, but not line 34, so child has stopped.
   Press F5 - debugger stops at line 34 in the child. Press F5 - child continues and exits. Parent stops at line 14. Press F5 and parent exits.
   
6. Running the program directly on Linux and attaching to the child process works fine.
   
7. Running the program directly on Linux and attaching to both the parent and child processes, pressing enter on Linux to continue the child, causes VS to stop at line 34 in the child, but pressing F5 is then the same as case 3 above.
[main.cpp.txt](https://github.com/Microsoft/VSLinux/files/1595214/main.cpp.txt)

**Comment by paulmaybee** [comment] 2018-01-08 20:43
Debug child process only works in gdb mode. It has no affect in gdbserver mode. I am able to reproduce your behavior and have opened a bug to track it. Look for a fix in a coming update. 

At this time I am not able to offer a workaround, but will continue to investigate to see if there is some way to get past this behavior.

**Comment by itodirel** [comment] 2018-11-27 01:39
@paulmaybee are there any updates on it? can we close it?

**Comment by paulmaybee** [comment] 2018-11-27 15:43
This is still an active issue.

**Comment by itodirel** [comment] 2020-03-24 04:42
Hi, we don't plan on supporting this for gdbserver at this time. If this is important to you, please open a suggestion to us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-24 04:42 UTC
Labels: closed, enhancement, feature
