### ISSUE TITLE
[Debugging] Array size limited to 50 (default or custom natvis)

### ISSUE THREAD

**Issue by FDCTLC** [Microsoft/VSLinux#333] opened 2018-09-17 15:32 UTC
* A brief description
Expanded vectors are limited to 50 elements regardless to the natvis configuration
* Expected results
Full vector expansion as in VC++
* Actual results (with build output window contents if applicable)
![image](https://user-images.githubusercontent.com/42431314/45632126-e5ed5180-ba9c-11e8-9ed0-db5c1db2b8ce.png)
![image](https://user-images.githubusercontent.com/42431314/45632171-f7cef480-ba9c-11e8-8367-3cae24258f75.png)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. 
VS 2017 15.8.4
WSL - Ubuntu 18.04 - GDB 8.1 - GCC 8.2.0
Linux 4.4.0-17134-Microsoft #285-Microsoft Thu Aug 30 17:31:00 PST 2018 x86_64 x86_64 x86_64 GNU/Linux
x86_64-linux-gnu

* Steps required to reproduce the error

  - ![image](https://user-images.githubusercontent.com/42431314/45633190-6f058800-ba9f-11e8-91e4-f4832285befd.png)

  - NATVIS (custom, but not working also the normal one):
![image](https://user-images.githubusercontent.com/42431314/45632550-e1756880-ba9d-11e8-9d7d-4732994c9ca7.png)
Size variable seems to be ignored

* Required packages and commands to install
  - Debugging ->Visualization File->$(LinuxNatvisPath)\stl.natvis " ShowDisplayString="true
  - Custom natvis (optional)

Thank you
FDC

**Comment by itodirel** [comment] 2019-01-15 09:12
@paulmaybee any comment on this?

**Comment by itodirel** [comment] 2019-03-21 05:39
close as duplicate of Microsoft/MIEngine#821

**Closed by itodirel** 2019-03-21 05:39 UTC
Labels: bug understood, investigating, question

**Comment by itodirel** [comment] 2020-03-20 03:19
We retired this issue list, here on Github. We now adopted and using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context in this current issue, please create a new issue on the Developer Community and mention it there. For existing issues which we can reproduce, or anything that is actionable to us, we will provide an update right here, in this thread. For new suggestions or issues, which at this time are in our roadmap, or we believe and have evidence that it will broadly and/or significantly benefit everyone, we will open a suggestion ticket, with the issue or suggestion, and link it here. For anything else, we recommend to please open a ticket on the Developer Community.
