### ISSUE TITLE
CMake target info extraction fails on some machines

### ISSUE THREAD

**Issue by devin122** [microsoft/VSLinux#196] opened 2017-10-16 15:44 UTC
I have 2 ubuntu vms. both running 16.04 LTS. One of them works fine, the other will fail during cache generation with the following 
```
1> -- Build files have been written to: /var/tmp/build/c51a3e8b-f143-c031-9b1f-d63a3ea68378/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriver.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriver.<ShakeHandAsync>d__61.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsync>d__28.MoveNext()
```

I've done a little bit of digging and it looks like it might be a buffering/timing issue. I collected logs of the cmake server interaction, by point VS at the following script instead of the cmake executable
```  
#!/bin/zsh
MY_DIR=$(readlink -e `dirname $0`)
LOGFILE=$MY_DIR/$DATE_STR.log
PAT="\\"
REPL="/"
ARG_STR=$(echo "'${^@//$PAT/$REPL}'")

if ((n = ${(M)#@:#server})); then
        echo "=================================" >> $MY_DIR/log.txt
        echo "cmake $ARG_STR" >> $MY_DIR/log.txt
        tee -a $MY_DIR/log.txt | "$MY_DIR/cmake" $@  | tee -a $MY_DIR/log.txt
else
        "$MY_DIR/cmake" $@
fi
```

Which yields the following log
```
=================================
cmake '-E' 'server' '--debug' '--experimental'

[== "CMake Server" ==[
{"supportedProtocolVersions":[{"isExperimental":true,"major":1,"minor":0}],"type                                                                                                                                                             ":"hello"}
]== "CMake Server" ==]
[== "CMake Server" ==[

{"cookie":"Visual Studio","type":"handshake","protocolVersion":{"major":1},"sour                                                                                                                                                             ceDirectory":"/var/tmp/src/c51a3e8b-f143-c031-9b1f-d63a3ea68378/Linux-Debug","bu                                                                                                                                                             ildDirectory":"/var/tmp/build/c51a3e8b-f143-c031-9b1f-d63a3ea68378/build/Linux-D                                                                                                                                                             ebug","generator":"Unix Makefiles"}

]== "CMake Server" ==]

[== "CMake Server" ==[

{"type":"quit"}

]== "CMake Server" ==]


[== "CMake Server" ==[
{"cookie":"Visual Studio","inReplyTo":"handshake","type":"reply"}
]== "CMake Server" ==]

[== "CMake Server" ==[
{"cookie":"","errorMessage":"Unknown command!","inReplyTo":"quit","type":"error"                                                                                                                                                             }
]== "CMake Server" ==]
```
Im not 100% convinced the ordering in the log perfect, due to the use of `tee` to log input and output like this. But it would appear the VS is not waiting for the response to its handshake, or its getting out of sync and thinking that the server's "hello" packet is the response. Although I'm not sure why this would only occur on one machine (and with 100% consistency)

**Comment by lukka** [comment] 2017-10-16 17:43
@devin122 thanks for the report. Please check the version of cmake on both machines, and whether they support "Server Mode" capability, thanks.

**Comment by devin122** [comment] 2017-10-17 14:42
Both are running identical 3.9.0 binaries (from the cmake download page), which support server mode

**Comment by mbikovitsky** [comment] 2017-11-04 19:57
I'm having this issue as well, and it appears to be triggered by zsh. When I switch the login shell to bash, the issue disappears.

Moreover, with some WinDbg sorcery we can take a look at the parameters passed to `libcmake.CMakeDaemonDriver.Expects` (the function at the top of the crash stack trace):

    string message = "{"cookie":"Visual Studio","type":"handshake","protocolVersion":{"major":1},"sourceDirectory":"/var/tmp/src/fcbc127b-5fdc-bd30-b9d0-42d8cc15789a/Linux-Debug","buildDirectory":"/var/tmp/build/fcbc127b-5fdc-bd30-b9d0-42d8cc15789a/build/Linux-Debug","generator":"Unix Makefiles"}"
    string expectedMessage = "{ 'cookie':'Visual Studio','inReplyTo':'handshake','type':'reply'}"

The `message` parameter is the string read from the SSH session with the cmake server, and is expected to be a handshake "ack". Instead, we get the actual handshake sent from Visual Studio (see the docs [here](https://cmake.org/cmake/help/v3.9/manual/cmake-server.7.html)).

I hope this will help in resolving the issue. Meanwhile, as a workaround, consider either switching the login shell to bash, or creating a dedicated user for remote builds with this shell.

**Comment by neverchanje** [comment] 2018-12-02 12:41
I used `chsh -s /bin/bash` to change the default shell from zsh to bash, and this issues fixed too. My host platform is ubuntu 18.04, VS version is Professional 2017, 15.9.3.

**Comment by YihaoPeng** [comment] 2018-12-24 09:11
Fixed by `chsh -s /bin/bash`.
My default terminal is `zsh` before the fix.

**Comment by itodirel** [comment] 2020-03-20 08:03
Thank you, tracked with, and planned to be addressed, in our roadmap: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-20 08:03 UTC
Labels: investigating, need repro

**Comment by itodirel** [comment] 2020-03-24 04:49
Thank you, tracked with, and planned to be addressed, in our roadmap: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.
