### ISSUE TITLE
Unable to setup remote linux connect

### ISSUE THREAD

**Issue by L-EARN** [Microsoft/VSLinux#142] opened 2017-05-12 11:39 UTC
Hi.

* A brief description

Connectivity Failure when trying to connect to a LAN server.

* Expected results

Connect fine.

* Actual results (with build output window contents if applicable)

The SSH server catch a packet integrity error and close the connect everytime.
As you can see in the image below, I can successfully connect to the my LAN Ubuntu computer using putty and tail the auth.log. I can also connect using SFTP. Visual Studio is faulting somewhere ... And it seems I'm the only one who have this problem on Internet.

Remote error output : **Packet integrity error (1 bytes remaining) at ../auth2-passwd.c:66 [preauth]**

![Picture](https://snag.gy/zShn8I.jpg)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware

Windows 10 Home x64 1703 15063.250
Visual Studio Community 2017 15.2 36430.4
Ubuntu 16.04 LTS x86 4.4.0-77-generic 98-Ubuntu SMP Wed Apr 26 08:33:44 UTC 2017 i686 athlon
gdb 7.11.1 + gdbserver
gcc 5.4.0 + gcc-4.8 4.8.5
OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016

**Comment by Raffa50** [comment] 2017-05-17 10:59
Look at this: https://github.com/Microsoft/BashOnWindows/issues/734
This helped me, I've changed the ssh door (however other problems)

**Comment by L-EARN** [comment] 2017-05-20 23:03
Hi @Raffa50 Changing the host SSH port didn't worked.
I don't have any SSH host service on my client (windows) computer also.

But thank you to try to resolve my issue.

I really think it's a bug in the networking code from Visual Studio. All the symptoms seems to go into that kind of problem.

**Comment by L-EARN** [comment] 2017-05-22 15:03
I am able to connect using keys.
It solved my issue. But the password method is still broken.

**Comment by zimmermegan** [comment] 2017-07-17 17:24
I also had the same issue, I could SSH in fine and dandy, but VSLinux for Visual Studio 2017 wouldn't connect. After [this fix](https://social.msdn.microsoft.com/Forums/vstudio/en-US/69075cf3-a1b7-4c4c-bbac-807e46426dc8/unable-to-add-ssh-connection-to-remote-system-in-visual-studio-2017?forum=vsdebug) and moving to the Visual Studio 2015 version and it worked (Still doesn't work on 2017).

**Comment by itodirel** [comment] 2017-08-10 00:55
this seems like a problem with your Linux system, I know that the Windows team owning WSL had fixed a bug here, but I'm not sure if it is this one; @robotdad any ideas?

**Comment by zimmermegan** [comment] 2017-08-14 14:25
Considering that it works fine with 2015 and not 2017, I don't think its a problem with my Linux system. I've opted to migrate all the code backwards to vs2015 rather than wrestle any longer with 2017

**Comment by mechanicalgux** [comment] 2017-11-06 07:53
Just had this problem and I found the solution.
In my case the SSH server on the linux distro (DietPi on RPI3) was Dropbear. I replaced it with openssh-server and Visual Studio now works fine with it.

**Comment by robotdad** [comment] 2017-11-06 17:47
That's interesting. We should look at what our problem with dropbear is, I wasn't aware of that. The original report from @L-EARN here is with openssh though. @lukka are there any logs that we could request to help get to the bottom of this?

**Comment by evakili** [comment] 2017-11-12 10:40
I've the same problem for a while (from first versions of VCLinux) and no success with any work around that could be found via Google. I'v had this problem with WSL before, but now I could see the problem with my Ubuntu 16.04 installation.
Is there any log generated by VS during connect?

**Comment by evakili** [comment] 2017-11-12 16:46
It seems that authentication to ssh server succeeded but suddenly client (VS) closes the connection. If I enter wrong password VS returns credentials error. But when I enter correct password it shows above error message (as in the first message in this issue).

**Comment by nickdnickd** [comment] 2018-01-29 23:01
@evakili I am exactly where you are right now. I can ssh from PuTTY and yet when I run
`sudo /usr/sbin/sshd -d -p 2222` on WSL (Ubuntu) and try to connect from VS2017 I see in the WSL server logs that the credentials were accepted but on the VS end it flags the port and host name

**Comment by itodirel** [comment] 2018-01-29 23:52
Can you try connecting again from Putty? It's possible your sshd server exited after the first connection?

**Comment by itodirel** [comment] 2018-01-29 23:53
@evakili, does your container allows multiple/simultaneous ssh connections? And can you confirm it's not configured to only allow one connection?

**Comment by nickdnickd** [comment] 2018-01-29 23:58
@itodirel I tried various of forms of connecting and disconnecting. I did find success by uninstalling and reinstalling openssh-server and running `sudo service ssh start` following advice from [here](https://www.dotnetcatch.com/2017/04/23/debugging-net-core-from-vs2017-on-windows-subsystem-for-linux/). Afterwards I was able to connect via VS2017

**Closed** 2018-01-31 00:18 UTC
Labels: external

**Comment by evakili** [comment] 2018-02-03 07:19
@itodirel Yes. I test several scenarios. I could connect to my Linux machine simultaneously with normal cli ssh connections.

**Comment by evakili** [comment] 2018-03-10 09:39
@lukka I have tested the scenario on many configurations and distributions without any success. I'm pretty sure that this is not a configuration error on Linux side. There is a problem in VS or client Windows system. I don't know why this thread is closed.
To clarify the error, is there any log generated by VSLinux?

**Comment by zhuxueluo** [comment] 2018-04-27 01:49
i got a connectivity problem too: ssh by putty is ok while ssh by vs is not. After i reinstall openssh-server, problems are solved. I guess this is because of wrong configuration of openssh-server.

**Comment by VladimirAkopyan** [comment] 2018-05-05 11:29
I have same issue - VS can;t connect, where-as putty is perfectly happy.

**Comment by CodyPannell** [comment] 2018-07-19 15:01
@lukka I'm also having this issue, I have SSH and SFTP running but they're running through dropbear. Is VS2017 incompatible with dropbear?

**Comment by raimand13** [comment] 2018-10-26 07:18
I have same issue too. but i get ssh and sftp logs from /var/log/auth.log :
-----------------
Oct 26 08:57:09 PC-Ubuntu systemd-logind[728]: New session 11 of user myuser.
Oct 26 08:57:09 PC-Ubuntu sshd[2862]: Connection from 192.168.56.1 port 25107 on 192.168.56.3 port 22
Oct 26 08:57:10 PC-Ubuntu sshd[2860]: User child is on pid 2888
Oct 26 08:57:10 PC-Ubuntu sshd[2862]: Accepted password for myuser from 192.168.56.1 port 25107 ssh2
Oct 26 08:57:11 PC-Ubuntu sshd[2862]: pam_unix(sshd:session): session opened for user myuser by (uid=0)
Oct 26 08:57:11 PC-Ubuntu systemd-logind[728]: New session 12 of user myuser.
Oct 26 08:57:11 PC-Ubuntu sshd[2862]: User child is on pid 2913
Oct 26 08:57:11 PC-Ubuntu sshd[2913]: Starting session: subsystem 'sftp' for myuser from 192.168.56.1 port 25107 id 0

//Here SFTP is called
Oct 26 08:57:11 PC-Ubuntu sftp-server[2914]: session opened for local user myuser from [192.168.56.1]
Oct 26 08:57:11 PC-Ubuntu sftp-server[2914]: received client version 3
Oct 26 08:57:11 PC-Ubuntu sftp-server[2914]: realpath "."
Oct 26 08:57:11 PC-Ubuntu sftp-server[2914]: realpath "/etc/os-release"
Oct 26 08:57:11 PC-Ubuntu sftp-server[2914]: lstat name "/usr/lib/os-release"
Oct 26 08:57:11 PC-Ubuntu sshd[2888]: Starting session: command for myuser from 192.168.56.1 port 25106 id 0
//Here client (vs 2017) close the connection

Oct 26 08:57:11 PC-Ubuntu sshd[2888]: Close session: user myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:11 PC-Ubuntu sshd[2888]: Starting session: command for myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:11 PC-Ubuntu sshd[2888]: Close session: user myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:11 PC-Ubuntu sshd[2888]: Starting session: command for myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:12 PC-Ubuntu sshd[2888]: Close session: user myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:12 PC-Ubuntu sshd[2888]: Starting session: command for myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:12 PC-Ubuntu sshd[2888]: Close session: user myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:12 PC-Ubuntu sshd[2888]: Starting session: command for myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:12 PC-Ubuntu sshd[2888]: Close session: user myuser from 192.168.56.1 port 25106 id 0
Oct 26 08:57:14 PC-Ubuntu sshd[2888]: Received disconnect from 192.168.56.1 port 25106:11: Connection terminated by the client.
Oct 26 08:57:14 PC-Ubuntu sshd[2888]: Disconnected from 192.168.56.1 port 25106
Oct 26 08:57:14 PC-Ubuntu sshd[2860]: pam_unix(sshd:session): session closed for user myuser
Oct 26 08:57:14 PC-Ubuntu sftp-server[2914]: session closed for local user myuser from [192.168.56.1]
Oct 26 08:57:14 PC-Ubuntu sshd[2913]: Close session: user myuser from 192.168.56.1 port 25107 id 0
Oct 26 08:57:14 PC-Ubuntu systemd-logind[728]: Removed session 11.
-----------------

**Comment by raimand13** [comment] 2018-10-26 11:50
I finally find out what was problem!!! i change debug level in sshd_config to DEGUG3 and also change SFTP degug level too in sshd_config like this '/usr/lib/openssh/sftp-server -l DEBUG3'. VS2017 run a few commands and then close the connection because OS arch is not match to 'x86_64' or 'amd64'.

VS 2017 SSH commands on connecting for Linux Remote Debugger

1. Login to SSH with user and passsword (or private key) 'This option doesn't matter!'
2. Open and close SFTP subsystem for test SFTP.
3. Run 'uname -m' command 'This command result must be 'amd64' or 'x86_64''
4. Run 'uname -r' command
5. Run 'g++ -v' command
6. Run 'gdbserver --version' command
7. Finally check all commands results by VS 2017

So i should install Ubuntu 'amd64'

**Comment by evakili** [comment] 2018-12-20 06:56
Also my problem is solved but in different way!

I have set the calendar of Windows to some local calendar (Persian Sonar Calendar: هجری شمسی). By changing it back to Gregorian calendar the problem is removed.

**Comment by jarlostensen** [comment] 2019-01-09 19:54
FWIW: I had a general issue with VS2017's connection to the linux subsystem failing the auth and followed these instructions which fixed it for me; https://superuser.com/questions/1111591/how-can-i-ssh-into-bash-on-ubuntu-on-windows-10

**Comment by ChristopherHogan** [comment] 2020-01-07 16:35
In my case, the connection was failing because of some `.bashrc` commands I was running. Temporarily move your `.bashrc` file to rule this out.
