### ISSUE TITLE
Unable to start program when trying to debug cmake project

### ISSUE THREAD

**Issue by DanielOdenbrandQlik** [Microsoft/VSLinux#197] opened 2017-10-19 08:49 UTC
I set up the Linux c++ development environment as per https://blogs.msdn.microsoft.com/vcblog/2017/04/11/linux-development-with-c-in-visual-studio/ and https://blogs.msdn.microsoft.com/vcblog/2017/08/25/visual-c-for-linux-development-with-cmake/. I also did the workaround to be able to open CMakeLists with Linux support enabled as per https://developercommunity.visualstudio.com/content/problem/128569/cmake-unusable-after-upgrading-to-154.html. 

I set up the minimal hello.cpp example with the corresponding CMakeList.txt and everything compiles fine. But when I try to debug the application I get the following error:

"
Unable to start program
'C:\......\CMakeBuilds\${workspaceHash}\build\Linux-Debug\hello-cmake.exe'

'C:\......\CMakeBuilds\${workspaceHash}\build\Linux-Debug\' is not a valid working directory
"

And quite correctly that path does not exist. On the other hand the folder for x86-Debug is in that folder even though I haven't compiled it. The program is indeed correctly compiled and runs fine on the Linux machine.

Why is VS trying to run something locally when I really want to run and debug on the remote machine? The setup looks fairly straight forward so I'm guessing there's some versioning issue or similar?

I'm running a VirtualBox environment with debian-stretch 9,1 OS as my remote Linux machine with gdbserver version 7.12.0, gcc 6.3.0 and gdb 7.12.0. On my Windows machine I have VS2017 with VC++ redistributable 14.11.25325.

Thanks for the nice work on introducing this feature though! It will be exciting to have it up and running!

**Comment by lukka** [comment] 2017-10-20 01:38
@DanielOdenbrandQlik which version of VS are you currently using? If you could, please try with [15.5 Preview](https://blogs.msdn.microsoft.com/visualstudio/2017/10/11/visual-studio-2017-version-15-5-preview/) and let us know.

**Comment by DanielOdenbrandQlik** [comment] 2017-10-20 07:01
Hi @lukka! I'm using 15.4 professional. I will try the preview and see how it goes!

**Comment by DanielOdenbrandQlik** [comment] 2017-10-20 07:44
@lukka, it works somewhat better! I can now run the program properly but it seems to ignore all breakpoints! 

`Breakpoint 1, main (argc=1, argv=0x7fffffffeb68) at /var/tmp/src/2dd642f5-b232-cb3a-b413-a93ca64d686b/Linux-Debug/hello.cpp:5
5	    std::cout << "Hello" << std::endl;
Hello
[Inferior 1 (process 24268) exited normally]
The thread 'hello-cmake' (0x5ecc) has exited with code 0 (0x0).
The program 'hello-cmake.exe' has exited with code 0 (0x0).
`

Looks like it's setting the breakpoint but it never stops at them.

**Comment by DanielOdenbrandQlik** [comment] 2017-10-23 14:01
Thanks for that observation, @inouiw. I'm quite certain I built the"$(buildRoot)\hellt-cmake" and not something else though. 

Anyway, still having issues with actually breaking when debugging

**Comment by lukka** [comment] 2017-10-23 19:42
Duplicate of #119

**Closed by lukka** 2017-10-23 19:42 UTC
