### ISSUE TITLE
Clean Target should remove additional copied files, as well as build-specific files

### ISSUE THREAD

**Issue by ddrinka** [microsoft/VSLinux#183] opened 2017-09-11 20:19 UTC
I have configured an AdditionalSourcesToCopyMapping which copies over needed external include files and libraries.

If I build and then clean, the files copied for compile are removed, but the additional files (also located under the "projects" directory remotely), are left intact.

I expect the clean target to treat additional sources and build sources the same, and either only delete the binary outputs (as a local clean would do), or to delete all the inputs (as remote clean currently does for build sources).

**Comment by itodirel** [comment] 2019-01-03 18:57
that is a good suggestion, and these should indeed be cleaned

**Comment by itodirel** [comment] 2020-03-24 04:24
We will won't fix this issue at this time, a fix for this can be accomplished with an post build step, or overriding a task to do the cleanup using the Execute command. If this is important to you, please open a issue to us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-24 04:24 UTC
Labels: bug
