### ISSUE TITLE
Login Freezing with Proxy

### ISSUE THREAD

**Issue by ghost** [Microsoft/VSLinux#88] opened 2017-01-13 15:12 UTC
I am trying to login using a private key and it seems to like my credentials because if I put the wrong credentials it will turn the boxes red but when I put the right credentials it gets past that and freezes. (I get the VS delay notification)
I think this has something to do with my company's proxy, we have NT LAN Manager setup. However, there is nothing strange with doing normal ssh or putty. Another thing I think that could be a problem is the gdbserver port. Just guesses is there a way I could get more information about what might be getting me stuck? 

I am using Visual Studio Professional 2015 with the most recent updates and I just re-installed the Linux development plugin. On linux I am using sles-release-12.1-1.331.x86_64, with gcc version 6.2.0 (GCC), GNU gdb (GDB) 7.12 ,GNU gdbserver (GDB) 7.12, OpenSSH_6.6.1p1.

**Comment by itodirel** [comment] 2017-08-21 22:55
Do you see the dialog responsive after about 30 seconds? Can you confirm that SFTP is enabled? 

Are you setting up a proxy or doing anything different when using Putty?

**Comment by willmsy32** [comment] 2017-10-13 11:15
I ran into almost the exact same situation except using a password instead of a private key. Nothing is responsive after this occurs, Visual Studio locks up. No issues when trying to connect to the server using PuTTY or transfer files with WinSCP. The solution for me ended up being a two-step process of deleting the login credential file you can find at %USERPROFILE%\AppData\Local\Microsoft\Linux\User Data\3.0 and clearing the entire contents of my user directory on the server before restarting Visual Studio.

**Comment by itodirel** [comment] 2018-11-27 01:19
Not able to reproduce on our side, closing tentatively, if this is still an issue please re-activate and we'll take a look with new information.

**Closed by itodirel** 2018-11-27 01:19 UTC
Labels: investigating
