### ISSUE TITLE
Could not start rsync command on the remote host

### ISSUE THREAD

**Issue by mqudsi** [Microsoft/VSLinux#341] opened 2018-09-26 18:31 UTC
On Visual Studio 15.9 Preview 2, I have a cmake project connecting to an Ubuntu 18.04 LTS hyper-v instance, which was working fine.

After using `cmake` locally (under WSL) in a `build` subdirectory of the project root, VS now fails to remotely rsync, with the following message:

> Copying files to remote machine...
> Could not start the 'rsync' command on the remote host, please install it using your system package manager.

(Is there a way to increase the verbosity of these messages?)

`rsync` is installed and invokable on the remote host.

**Comment by lukka** [comment] 2018-09-27 18:46
@mqudsi the problem must be that you need to kill rsync on the WSL instance (e.g. pkill rsync).
The root cause is that our logic of finding a spare tcp port is faulty on WSL (as cat /proc/net/tcp would tell you all port are free, but that's not true), and that in some cases we do not terminate the remote rsync process. We are working a better experience about this.

**Comment by mqudsi** [comment] 2018-09-27 21:14
@lukka I don't think WSL is a factor here, as this is running in Visual Studio under Windows and the remote instance VSLinux is configured to use is a Hyper-V Ubuntu instance.

The "cmake under WSL" referenced in OP is an "out-of-band" operation that I manually performed that should have no bearing on any of the steps before or after.

**Comment by mqudsi** [comment] 2018-09-30 16:56
Your suggested workaround (`sudo killall -9 rsync`) did the trick, but to emphasize, this was on a Real Linux (TM) remote host, so it would seem that the problem is with general free port detection under Linux and not just under WSL.

Thank you for the workaround!

**Comment by mqudsi** [comment] 2018-10-02 01:13
I presume you mean when this error is encountered and not normally?

**Comment by mqudsi** [comment] 2018-10-04 22:10
Just experienced this again (Debian remote host), here's the output of `cat /proc/net/tcp` when that happens:

```
mqudsi@debianvm ~/fish-shell> cat /proc/net/tcp
  sl  local_address rem_address   st tx_queue rx_queue tr tm->when retrnsmt   uid  timeout inode                                                     
   0: 00000000:0016 00000000:0000 0A 00000000:00000000 00:00000000 00000000     0        0 21593 1 ffff9ee6f5012800 100 0 0 10 0                     
   1: 0100007F:115C 00000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 92435 1 ffff9ee63642d040 100 0 0 10 0                     
   2: 0100007F:115D 00000000:0000 0A 00000000:00000000 00:00000000 00000000  1000        0 94432 1 ffff9ee63642d7c0 100 0 0 10 0    
```

`sudo killall -9 rsync` took care of it.

**Comment by AliAskari** [comment] 2018-11-27 02:39
I have also had this issue multiple times. On both a real Linux box and a VM. Killing the rsync has always fixed it.

**Comment by itodirel** [comment] 2019-01-15 09:18
@elizabethmorrow you had a fix for this, can you take a look if it's the same thing?

**Comment by itodirel** [comment] 2019-03-21 05:49
this should be fixed now, please let us know otherwise

**Closed by itodirel** 2019-03-21 05:49 UTC
Labels: fixed, investigating

**Comment by duzenko** [comment] 2019-09-30 15:09
Is this fixed for WSL as well?

**Comment by quantum-ai-01** [comment] 2020-02-17 11:12
> this should be fixed now, please let us know otherwise

facing this issue while adding a remote connection.

An error has occured. Could not start the 'rsync' command on the remote host, please install it using your system package manager. Please see https://aka.ms/AA23jat for troubleshooting. Please see C:\Users\hab20\AppData\Local\Temp\2\vslinux_header_update_log.txt for more information. Please see https://aka.ms/AA23jat for troubleshooting.

**Comment by itodirel** [comment] 2020-03-20 02:46
We believe this should be fixed. @quantum-ai-01 what version of VS are you using? If this is still an issue to you, please open a issue on the Developer Community.
