### ISSUE TITLE
Cannot debug in gdb mode when terminal is in raw mode

### ISSUE THREAD

**Issue by AliAskari** [Microsoft/VSLinux#96] opened 2017-01-25 03:01 UTC
We use the following code snippet to change the terminal to raw mode:

	#include <termios.h>
	#include <unistd.h>

	int main()
	{
		struct termios termios_p;
		tcgetattr(STDIN_FILENO, &termios_p);
		termios_p.c_cc[VMIN] = 1;
		termios_p.c_cc[VTIME] = 0;
		termios_p.c_lflag &= ~(ECHO | ICANON);
		tcsetattr(STDIN_FILENO, TCSANOW, &termios_p);

	        return 0;
	}

It lets us to take user inputs F1, F2, etc and switch the terminal to a different view. There is no problem when we debug in gdbserver mode. But when I try the gdb mode the debugging stops, at this line: tcsetattr(...), with the following error:

    + Stopped (tty output) error

I cannot continue and the only option is to stop debugging. I do not have this issue when I run gdb natively.

Here are version details:
Visual Studio: 2017RC
OS & arch: CentOS 7.2 x86_64
gcc version: 4.8.5
gdb & gdbserver version: 7.9
Default shell: Bash

**Comment by stanthomas** [comment] 2017-01-26 23:22
Probably the same as issue #33

**Comment by itodirel** [comment] 2017-08-25 00:39
We weren't passing -tty to gdb when running it, I think that was the underlying cause, currently we're almost done with making the Linux console working in gdb mode, and we are passing tty to gdb; @lukka FYI, can you include this scenario in your testing on gdb with Linux Console?

**Comment by AliAskari** [comment] 2017-08-25 05:13
@itodirel Cool. Is there a way to test your daily builds?

**Comment by itodirel** [comment] 2017-09-05 22:52
@lukka

**Comment by lukka** [comment] 2017-09-05 22:59
Duplicate of #129

**Closed by lukka** 2017-09-05 22:59 UTC
Labels: fixed
