### ISSUE TITLE
Recreate project directory if it doesn't exist

### ISSUE THREAD

**Issue by pps83** [Microsoft/VSLinux#163] opened 2017-07-24 05:23 UTC
My test program create lots of log file and I simply remove entire tree on my remote linux. Now I cannot build or run this project on VS. What a fail!

![image](https://user-images.githubusercontent.com/1614246/28509213-71294aea-6ff5-11e7-96a6-c2beeb18d65b.png)

**Comment by pps83** [comment] 2017-07-24 05:29
No matter what I tried, I couldn't fix it. Appears VS-Linux was trying to be smart and refused to update src file as it wasn't modified.
I tried to switch different machines etc... perhaps when I switch to another linux machine it will also fail thinking that file is up to date even if it wasn't uploaded that server previously.

**Comment by stanthomas** [comment] 2017-07-24 16:43
See #100

**Comment by itodirel** [comment] 2017-08-09 23:35
This error comes from debugging, specifically, it is saying that your are trying to debug a program (file) that does not exist on the Linux system, so I'm not sure I understand the comment about creating the directory, that won't solve the problem here.

Could you tell me how your build is configured? Is it a Makefile?

**Comment by braindeaddeveloper** [comment] 2017-08-10 10:05
Is this related to #164 ?

**Comment by itodirel** [comment] 2017-08-24 22:58
It could be related, indeed. That bug with removing the directory is now fixed.

**Comment by itodirel** [comment] 2017-09-19 21:21
Closing due to inactivity for tracking purposes, if you can reproduce it, please reactive, or just ping us and we'll reactive the issue.

**Closed by itodirel** 2017-09-19 21:21 UTC
Labels: discussion, investigating, need repro
