### ISSUE TITLE
How can I automatically copy content files to remote output directory?

### ISSUE THREAD

**Issue by SamuelHenderson** [Microsoft/VSLinux#157] opened 2017-07-10 19:39 UTC
* Brief description:
I have a image file "texture.png" that is in my Visual Studio Project folder. In texture.png's "Properties" panel of the 'Solution Explorer' I have the following properties set:

```
(Name):                 texture.png
Content:                True
File Type:              Bitmap
Full Path:              c:\<path_to_vs2015_projects>\CrossPlatformApp\LinuxApp\texture.png
Included in Project: True
Relative Path:         texture.png
```
I have 'Copy Remotely' and 'Copy to Output Directory' set to 'Yes' in the 'Copy Sources'  Property Page of texture.png (I accessed this by right clicking the file and selecting properties).

* Expected results
texture.png would be in the following directory:
`/home/shenderson/projects/LinuxApp/bin/x64/Debug/`

* Actual results (with build output window contents if applicable)
texture.png is not located in the `bin/x64/Debug/` directory in Linux.  I'm not seeing any 'copy errors' or permissions related errors so I would assume it should be copied?

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc:
I am using (Windows):
```
Windows 7 Professional
Visual Studio 2015 (14.0.25431.01)
Visual C++ for Linux Development (1.0.7)
```
(Linux):
```
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-514.21.2.el7.x86_64
Architecture: x86-64
g++ (GCC) 4.8.5 20150623 (Red Hat 4.8.5-11)
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-94.el7
```

* Steps required to reproduce the error

1. Create a new Visual C++ For Linux project 
2. Create a basic "Hello World!" console application and verify it compiles and runs on remote (Linux) machine.
3. Add a text file (or any content/data file) to the Project and set it's 'Copy Remotely' and  'Copy To Output Directory' properties to 'Yes'.
4. Clean and Build the project.
5. Check the remote output directory for the content file.

* Required packages and commands to install
```
gcc,
g++
gdb
```

**Comment by SamuelHenderson** [comment] 2017-07-10 20:20
I should also note that I am interested in any work-arounds (like build events) that can be used to counter this problem.

**Comment by wtof1996** [comment] 2017-07-13 05:29
I have the same problem, but I found my files in the remote project directory( ~/projects/$(ProjectName)/).
So you need copy them manually in  Build Events (You can see some remote events, choose the one you want):

```
cp ~/projects/$(ProjectName)/<File To be copyed> 
 ~/projects/$(ProjectName)/bin/$(PlatformTarget)/$(Configuration)
```

**Comment by itodirel** [comment] 2017-08-10 00:00
this is a bug that we recently fixed, the fix will be available in 15.4 Preview 2, the workaround is to copy it in a Build Event

**Comment by SamuelHenderson** [comment] 2017-11-08 14:28
I just tested this out with a new project and it does not seem to be fixed.

**Comment by itodirel** [comment] 2018-01-03 02:47
Could you tell us what build of VS you were using? @lukka assigning to you as you fixed it

**Comment by itodirel** [comment] 2018-01-03 02:48
The other thing is that they might be copied to the corresponding remote directory, and not the output directory, so you might have to take that into account. That part is currently by design.

**Comment by lukka** [comment] 2018-01-04 19:15
@SamuelHenderson the Content files are copied along the sources, so you should you should find it on the remote machine under the Remote Build Project directory.

The bug is that the Copy To Output Directory option is not fulfilled.

**Comment by itodirel** [comment] 2018-01-05 00:42
The  Copy To Output Directory bug is now fixed

**Closed** 2018-11-27 01:36 UTC
Labels: bug
