### ISSUE TITLE
Relative Additional Include Directories are not handled correctly

### ISSUE THREAD

**Issue by jessebenson** [microsoft/VSLinux#325] opened 2018-08-17 19:24 UTC
**Description**
If both the AdditionalIncludeDirectories and ClCompile/ClInclude contain relative paths, the remote build fails.  Setup:

src/ProjectA/ProjectA.vcxproj
src/ProjectA/main.cpp
src/common/helper.h
src/common/helper.cpp

src/ProjectA/ProjectA.vcxproj:
```
<AdditionalIncludeDirectories>../common</AdditionalIncludeDirectories>
<ClInclude Include="../common/helper.h" />
<ClCompile Include="../common/helper.cpp" />
<ClCompile Include="main.cpp" />
```

This generates the following layout on the remote:
~/projects/ProjectA/ProjectA/main.cpp
~/projects/ProjectA/common/helper.cpp
~/projects/ProjectA/common/helper.h

And the build command that fails to get the correct include path:
%> g++ -c -x c++ **/home/jesseb/projects/ProjectA/ProjectA/main.cpp -I /home/jesseb/projects/ProjectA/../common** ...

**Expected results**
For Windows .vcxproj, the working directory is the .vcxproj directory, so relative include directories/etc. work as expected.

For Linux .vcxproj, the working directory is set to (e.g.) ~/projects/ProjectA, even when the project directory is adjusted to ~/projects/ProjectA/ProjectA like above.

Visual Studio 2017 version 15.8.0 Preview 5.0

**Comment by heppth** [comment] 2018-09-19 15:09
I have the same problem. Please see [at stackoverflow](https://stackoverflow.com/questions/52381645/visual-studio-15-8-uses-wrong-include-paths-for-cross-compiling-g-on-linux?noredirect=1#comment91722493_52381645)

**Comment by yuehuang010** [comment] 2019-01-30 19:38
Hi, we recently discovered that a bug that in Additional Include Directory "include" fails but "./include" succeeds.  See if that helps your case.
If still has issues, can you share a sample of your project?  
Thanks

**Comment by itodirel** [comment] 2020-03-24 06:14
Dupe of #68

**Closed by itodirel** 2020-03-24 06:14 UTC
Labels: bug, bug understood
