### ISSUE TITLE
Connection failure on build, login works fine

### ISSUE THREAD

**Issue by jarekSig** [Microsoft/VSLinux#76] opened 2016-12-05 07:28 UTC
When I build the project for the first time, I get the connection setup screen.
I enter the username, and password - the screen stays for a moment and disappears then the build starts. But then it fails, with the following:
1>------ Build started: Project: Configuration, Configuration: Debug x64 ------
1>  Validating architecture
1>  Validating sources
1>  Copying sources remotely
1>C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Application Type\Linux\1.0\Linux.Common.targets(88,5): error : Could not connect to the remote system. Please verify your connection settings, and that your machine is on the network and reachable.
2>------ Build started: Project: VFIC, Configuration: Debug x64 ------
========== Build: 1 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Now I know it can connect, because the login screen works, Trying an incorrect password makes it fail so I know it's able to connect and authenticate the user.
Secondly I can connect using telnet to that port and can use ssh session just fine as well.

I am using v1.05 on Visual Studio 2015 Update 3.

When I connect via "telnet devsyd805 2222" it connects and I get the following version numer "SSH-2.0-OpenSSH_7.3"

In addition, I can use SCP and SFTP to connect and copy files just fine as well, on the same port.

**Comment by itodirel** [comment] 2016-12-22 00:25
Can you try the 1.0.6 version of the extension, we made some fixes in this area and we believe this should be fixed now.

**Comment by hgpatswu** [comment] 2016-12-22 03:04
I also get the same error.
I am using V 1.0.6 on Visual Studio 2017 RC.

**Comment by itodirel** [comment] 2016-12-22 03:06
Could you share the build log in diagnostic verbosity?

**Comment by hgpatswu** [comment] 2016-12-22 03:08
I have tried many times. Sometimes I will meet other problems. This time is "Unable to start debugging. Unexpected GDB output from command "-interpreter -exec console" Remote connection closed.

**Comment by itodirel** [comment] 2016-12-22 03:10
that sounds like it's caused because the build failed and the program is not on the remote system

**Comment by hgpatswu** [comment] 2016-12-22 03:13
It looks like the connection is very unstable. I'm considering abandoning VS for Linux C++ development.

**Comment by itodirel** [comment] 2016-12-22 05:23
hgpatswu, I'm sorry to hear that. Would it be possible to contact us directly at vcpplinux-support@microsoft.com or me at itodirel@microsoft.com? So we can get to the bottom of it? I'm confident we can figure out what's going on and fix it for you. 

Can you confirm you are on Visual Studio 2017 RC2? Could you also share how many connections do you have in Connection Manager? The running theory that I have right now is that because one of our previous bugs (we fixed it in RC.2), didn't supply the remote machine used for builds in one of the MSBUILD tasks, but did on the others. When not supplied, it defaulted to the first successful connection. It's possible that you might have added two or more connection connections, and if you're overriding the default remote target, it will try to connect to the incorrect machine, but only one of the tasks. And to the correct machine on the rest. So it would manifest exactly like your Minimal verbosity build log shows.

For a quick check, you can go to the Connection Manager in Tools Options, and remove all the machines, except the one that you are connecting to.

Regarding the build log, if you can get us that it would also help a lot to figure out what's wrong. First change the build verbosity in Tools - Options - Projects and Solutions - Build and Run - MSBuild project build output verbosity, to Diagnostic. Note that this is the first field in the UI, not the second one. Then please do a Rebuild on your Solution. Then switch to the Output Window, and please share the build log with us.

**Comment by jarekSig** [comment] 2016-12-22 22:41
@itodirel 
I have tried with version 1.0.6 but unfortunately it was the same result. I have turned on verbose output in Visual Studio and have attached the file (it's large!). I have also turned on debugging in the SSH server and the output is below:

```
debug1: sshd version OpenSSH_7.3, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: private host key #0: ssh-rsa SHA256:l35ijaM/vULik+eBSaaxFfFRL401F5GUU8Cs/LnTsJs
debug1: setgroups() failed: Operation not permitted
debug1: rexec_argv[0]='/home/mitek/openssh-7.3p1/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-f'
debug1: rexec_argv[3]='/home/mitek/config/ssh/sshd_config'
debug1: rexec_argv[4]='-h'
debug1: rexec_argv[5]='/home/mitek/config/ssh/jarek_ssh_key'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
socket: Address family not supported by protocol
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 4 out 4 newsock 4 pipe -1 sock 7
debug1: inetd sockets after dupping: 3, 3
Connection from 10.80.34.25 port 13957 on 10.80.35.2 port 2222
debug1: Client protocol version 2.0; client software version Ssh.SshClient.0.0.1
debug1: no match: Ssh.SshClient.0.0.1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.3
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group-exchange-sha256
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha1 compression: none
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha1 compression: none
debug1: expecting SSH2_MSG_KEX_DH_GEX_REQUEST
debug1: SSH2_MSG_KEX_DH_GEX_REQUEST received
WARNING: could open open /usr/local/etc/moduli (No such file or directory), using fixed modulus
debug1: SSH2_MSG_KEX_DH_GEX_GROUP sent
debug1: expecting SSH2_MSG_KEX_DH_GEX_INIT
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
Connection closed by 10.80.34.25 port 13957
debug1: do_cleanup
```
[visualstudio.txt](https://github.com/Microsoft/VSLinux/files/669990/visualstudio.txt)

**Comment by jarekSig** [comment] 2016-12-22 23:10
When I use an SCP client to successfully connect to this same service, i get the below debug:
`
debug1: sshd version OpenSSH_7.3, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: private host key #0: ssh-rsa SHA256:l35ijaM/vULik+eBSaaxFfFRL401F5GUU8Cs/LnTsJs
debug1: setgroups() failed: Operation not permitted
debug1: rexec_argv[0]='/home/mitek/openssh-7.3p1/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-f'
debug1: rexec_argv[3]='/home/mitek/config/ssh/sshd_config'
debug1: rexec_argv[4]='-h'
debug1: rexec_argv[5]='/home/mitek/config/ssh/jarek_ssh_key'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
socket: Address family not supported by protocol
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 4 out 4 newsock 4 pipe -1 sock 7
debug1: inetd sockets after dupping: 3, 3
Connection from 10.80.34.25 port 14771 on 10.80.35.2 port 2222
debug1: Client protocol version 2.0; client software version WinSCP_release_5.7.2
debug1: match: WinSCP_release_5.7.2 pat WinSCP_release_4*,WinSCP_release_5.0*,WinSCP_release_5.1*,WinSCP_release_5.5*,WinSCP_release_5.6*,WinSCP_release_5.7,WinSCP_release_5.7.1,WinSCP_release_5.7.2,WinSCP_release_5.7.3,WinSCP_release_5.7.4 compat 0x00004000
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.3
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group14-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEXDH_INIT
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: KEX done
debug1: userauth-request for user mitek service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for mitek from 10.80.34.25 port 14771 ssh2
debug1: userauth-request for user mitek service ssh-connection method keyboard-interactive
debug1: attempt 1 failures 0
debug1: keyboard-interactive devs
debug1: auth2_challenge: user=mitek devs=
debug1: kbdint_alloc: devices ''
Failed keyboard-interactive for mitek from 10.80.34.25 port 14771 ssh2
debug1: userauth-request for user mitek service ssh-connection method password
debug1: attempt 2 failures 1
Could not get shadow information for mitek
Accepted password for mitek from 10.80.34.25 port 14771 ssh2
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch_20
debug1: server_input_channel_open: ctype session rchan 256 win 2147483647 max 16384
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_channel_req: channel 0 request simple@putty.projects.tartarus.org reply 0
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req simple@putty.projects.tartarus.org
debug1: server_input_channel_req: channel 0 request subsystem reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req subsystem
debug1: subsystem: internal-sftp
Starting session: subsystem 'sftp' for mitek from 10.80.34.25 port 14771 id 0
^CExiting on signal 2
debug1: do_cleanup
mitek@helium800s:~/openssh-7.3p1> ~/openssh-7.3p1/sshd -d -f ~/config/ssh/sshd_config -h ~/config/ssh/jarek_ssh_key
/home/mitek/config/ssh/sshd_config line 97: Unsupported option UsePAM
debug1: sshd version OpenSSH_7.3, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: private host key #0: ssh-rsa SHA256:l35ijaM/vULik+eBSaaxFfFRL401F5GUU8Cs/LnTsJs
debug1: setgroups() failed: Operation not permitted
debug1: rexec_argv[0]='/home/mitek/openssh-7.3p1/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-f'
debug1: rexec_argv[3]='/home/mitek/config/ssh/sshd_config'
debug1: rexec_argv[4]='-h'
debug1: rexec_argv[5]='/home/mitek/config/ssh/jarek_ssh_key'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
socket: Address family not supported by protocol
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 4 out 4 newsock 4 pipe -1 sock 7
debug1: inetd sockets after dupping: 3, 3
Connection from 10.80.34.25 port 14784 on 10.80.35.2 port 2222
debug1: Client protocol version 2.0; client software version WinSCP_release_5.7.2
debug1: match: WinSCP_release_5.7.2 pat WinSCP_release_4*,WinSCP_release_5.0*,WinSCP_release_5.1*,WinSCP_release_5.5*,WinSCP_release_5.6*,WinSCP_release_5.7,WinSCP_release_5.7.1,WinSCP_release_5.7.2,WinSCP_release_5.7.3,WinSCP_release_5.7.4 compat 0x00004000
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.3
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group14-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEXDH_INIT
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: KEX done
debug1: userauth-request for user mitek service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for mitek from 10.80.34.25 port 14784 ssh2
debug1: userauth-request for user mitek service ssh-connection method keyboard-interactive
debug1: attempt 1 failures 0
debug1: keyboard-interactive devs
debug1: auth2_challenge: user=mitek devs=
debug1: kbdint_alloc: devices ''
Failed keyboard-interactive for mitek from 10.80.34.25 port 14784 ssh2
debug1: userauth-request for user mitek service ssh-connection method password
debug1: attempt 2 failures 1
Could not get shadow information for mitek
Accepted password for mitek from 10.80.34.25 port 14784 ssh2
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch_20
debug1: server_input_channel_open: ctype session rchan 256 win 2147483647 max 16384
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_channel_req: channel 0 request simple@putty.projects.tartarus.org reply 0
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req simple@putty.projects.tartarus.org
debug1: server_input_channel_req: channel 0 request shell reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req shell
Starting session: shell for mitek from 10.80.34.25 port 14784 id 0
``

**Comment by itodirel** [comment] 2016-12-23 05:59
Can you try connecting using SFTP as well, and see if that works?

We are not using SCP for file transfers, we are using SFTP, while it does seem that your SCP server is using SFTP, it might be that SFTP is disabled.

**Comment by jarekSig** [comment] 2016-12-25 23:24
@itodirel 
Sure, SFTP also works fine, here is the debug output from SSH server:
```
debug1: sshd version OpenSSH_7.3, OpenSSL 1.0.1i-fips 6 Aug 2014
debug1: private host key #0: ssh-rsa SHA256:l35ijaM/vULik+eBSaaxFfFRL401F5GUU8Cs/LnTsJs
debug1: setgroups() failed: Operation not permitted
debug1: rexec_argv[0]='/home/mitek/openssh-7.3p1/sshd'
debug1: rexec_argv[1]='-d'
debug1: rexec_argv[2]='-f'
debug1: rexec_argv[3]='/home/mitek/config/ssh/sshd_config'
debug1: rexec_argv[4]='-h'
debug1: rexec_argv[5]='/home/mitek/config/ssh/jarek_ssh_key'
debug1: Set /proc/self/oom_score_adj from 0 to -1000
debug1: Bind to port 2222 on 0.0.0.0.
Server listening on 0.0.0.0 port 2222.
socket: Address family not supported by protocol
debug1: Server will not fork when running in debugging mode.
debug1: rexec start in 4 out 4 newsock 4 pipe -1 sock 7
debug1: inetd sockets after dupping: 3, 3
Connection from 10.80.34.25 port 12407 on 10.80.35.2 port 2222
debug1: Client protocol version 2.0; client software version WinSCP_release_5.7.2
debug1: match: WinSCP_release_5.7.2 pat WinSCP_release_4*,WinSCP_release_5.0*,WinSCP_release_5.1*,WinSCP_release_5.5*,WinSCP_release_5.6*,WinSCP_release_5.7,WinSCP_release_5.7.1,WinSCP_release_5.7.2,WinSCP_release_5.7.3,WinSCP_release_5.7.4 compat 0x00004000
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.3
debug1: list_hostkey_types: ssh-rsa,rsa-sha2-512,rsa-sha2-256
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: diffie-hellman-group14-sha1
debug1: kex: host key algorithm: ssh-rsa
debug1: kex: client->server cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: kex: server->client cipher: aes256-ctr MAC: hmac-sha2-256 compression: none
debug1: expecting SSH2_MSG_KEXDH_INIT
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 4294967296 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: KEX done
debug1: userauth-request for user mitek service ssh-connection method none
debug1: attempt 0 failures 0
Failed none for mitek from 10.80.34.25 port 12407 ssh2
debug1: userauth-request for user mitek service ssh-connection method keyboard-interactive
debug1: attempt 1 failures 0
debug1: keyboard-interactive devs
debug1: auth2_challenge: user=mitek devs=
debug1: kbdint_alloc: devices ''
Failed keyboard-interactive for mitek from 10.80.34.25 port 12407 ssh2
debug1: userauth-request for user mitek service ssh-connection method password
debug1: attempt 2 failures 1
Could not get shadow information for mitek
Accepted password for mitek from 10.80.34.25 port 12407 ssh2
debug1: Entering interactive session for SSH2.
debug1: server_init_dispatch_20
debug1: server_input_channel_open: ctype session rchan 256 win 2147483647 max 16384
debug1: input_session_request
debug1: channel 0: new [server-session]
debug1: session_new: session 0
debug1: session_open: channel 0
debug1: session_open: session 0: link with channel 0
debug1: server_input_channel_open: confirm session
debug1: server_input_channel_req: channel 0 request simple@putty.projects.tartarus.org reply 0
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req simple@putty.projects.tartarus.org
debug1: server_input_channel_req: channel 0 request subsystem reply 1
debug1: session_by_channel: session 0 channel 0
debug1: session_input_channel_req: session 0 req subsystem
debug1: subsystem: internal-sftp
Starting session: subsystem 'sftp' for mitek from 10.80.34.25 port 12407 id 0
```

**Comment by itodirel** [comment] 2016-12-29 01:51
Can you share with me the build log, in diagnostic? My email is itodirel@microsoft.com, if you need to send a large file.

**Comment by jarekSig** [comment] 2016-12-29 03:55
@itodirel No problem, here it is:
[vslinux.txt](https://github.com/Microsoft/VSLinux/files/676575/vslinux.txt)

**Comment by itodirel** [comment] 2016-12-30 00:45
I noticed that you're using port 2222 for SSH, is it possible that you're using a different port for SFTP? I'm not sure if I'm reading the log correctly, but is it port 12407 for SFTP and port 2222 for SSH?

**Comment by jarekSig** [comment] 2017-01-03 22:10
@itodirel I'm including the sshd_config file below. 
So if I understand what you are asking, are we talking the difference between an active and passive SFTP?
[sshd_config.txt](https://github.com/Microsoft/VSLinux/files/683356/sshd_config.txt)

**Comment by bikeaccdnt** [comment] 2017-01-06 01:35
I am having same problem. I can login to ssh but get There are not remote machines configured for remote builds. Please configure a machine using Tools Options / Cross Platform. Frustrating

**Comment by itodirel** [comment] 2017-01-06 02:29
@jarekSig just to clarify, when you are using an external sftp client and it's working, do you specify port 2222 there as well, or do you specify a different port, or you do not specify a port at all?

Could you tell us the system name, version and bitness (64-bit or x86) that you're using? Could you also confirm whether this system had any special configuration?

**Comment by jarekSig** [comment] 2017-01-06 03:40
@itodirel I do not specify a port in the WinSCP client.
If I use command line SFTP from linux:
mitek@helium800s:~/> sftp -P 2222 mitek@helium800s
mitek@helium800s's password:
Connected to helium800s.
>

Note that I specify the port 2222 there.
So the SSHd running on 2222 is a new version. There is an older version running on 22 by default but this version does not seem to work at all with VS (It can't even validate my login details). Hence I setup a new SSHd on port 2222. At least with that one, VS can authenticate...

This a company machine, so I can't replace the one running on default 22. But i do believe that it's correctly setup to tunnel ftp over port 2222, because otherwise the above command would not work. It may well be I have set something up incorrectly or different to default, but I did not really change the default sshd_config file.

**Comment by itodirel** [comment] 2017-01-06 03:43
@bikeaccdnt I was able to reproduce this issue, we will have a fix for that ASAP. Please note that your issue is not related to the issue mentioned at the beginning of this post and experienced by @jarekSig

**Comment by itodirel** [comment] 2017-01-06 03:44
@jarekSig Could you tell me the system name, version and bitness (64-bit or x86) that you're using?

**Comment by jarekSig** [comment] 2017-01-06 03:50
@itodirel Sure it's 64-bit, SUSE 12.1... the full details are below...
``
mitek@helium800s:~/projects/VFIC> cat /etc/*-release
NAME="SLES"
VERSION="12-SP1"
VERSION_ID="12.1"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP1"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp1"
SUSE Linux Enterprise Server 12 (x86_64)
VERSION = 12
PATCHLEVEL = 1
# This file is deprecated and will be removed in a future service pack or release.
# Please check /etc/os-release for details about this release.
``

**Comment by itodirel** [comment] 2017-08-21 23:03
@bikeaccdnt, the fix that I mentioned is now available in Preview 1 of Visual Studio 2017

**Comment by itodirel** [comment] 2017-08-21 23:07
@jarekSig sorry, I still wasn't able to reproduce the issue and still investigating, are you still able to reproduce it on the latest version of Visual Studio?

**Comment by itodirel** [comment] 2018-01-26 22:16
closing due to no reply, if you can still repro, please re-activate

**Closed by itodirel** 2018-01-26 22:16 UTC
Labels: fixed, investigating
