### ISSUE TITLE
VS 15.8 prev 3 reports missing rsync during header download

### ISSUE THREAD

**Issue by boskars** [microsoft/VSLinux#306] opened 2018-07-03 12:03 UTC
**During download of headers following is reported, although rsync is installed on the remote system:**

![billede](https://user-images.githubusercontent.com/25032095/42218319-76ed5d8a-7ec8-11e8-90a5-8b638baeacbf.png)

**vslinux_header_update_log.txt contains:**

liblinux.IO.RsyncException: Could not start the 'rsync' command on the remote host, please install it using your system package manager. ---> liblinux.IO.RsyncException: Starting daemon failed, did not find process ID
   at liblinux.IO.RemoteRsyncDaemon.Start()
   at liblinux.IO.Rsync.StartRemoteServer(RemoteRsyncDaemon daemon)
   --- End of inner exception stack trace ---
   at liblinux.IO.Rsync.StartRemoteServer(RemoteRsyncDaemon daemon)
   at liblinux.IO.Rsync.PrepareForDirectorySync(Guid sessionID, String localPath, String remotePath, RsyncDirection direction, RemoteRsyncDaemon daemon, RsyncVerbosity verbosity, Boolean recursive, List`1 includes, List`1 excludes, String customOptions)
   at liblinux.IO.Rsync.SyncDirectory(String sourcePath, String destinationPath, RsyncDirection direction, CancellationToken token, String cmdLineFlags, List`1 includes, List`1 excludes, RsyncVerbosity verbosity, Boolean recursive, String customOptions)
   at liblinux.Services.RsyncRemoteCompilerIOImpl.DownloadDirectories(String[] remotePaths, String[] localPaths)
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)

**when I enter rsync in my terminal window I get:**

root@imx6ul-var-dart:/tmp# rsync
rsync  version 3.1.2  protocol version 31
Copyright (C) 1996-2015 by Andrew Tridgell, Wayne Davison, and others.
Web site: http://rsync.samba.org/
Capabilities:
    64-bit files, 64-bit inums, 32-bit timestamps, 64-bit long ints,
    socketpairs, hardlinks, symlinks, no IPv6, batchfiles, inplace,
    append, ACLs, xattrs, iconv, symtimes, prealloc

rsync comes with ABSOLUTELY NO WARRANTY.  This is free software, and you
are welcome to redistribute it under certain conditions.  See the GNU
General Public Licence for details.

rsync is a file transfer program capable of efficient remote update
via a fast differencing algorithm.

Usage: rsync [OPTION]... SRC [SRC]... DEST
  or   rsync [OPTION]... SRC [SRC]... [USER@]HOST:DEST
  or   rsync [OPTION]... SRC [SRC]... [USER@]HOST::DEST
  or   rsync [OPTION]... SRC [SRC]... rsync://[USER@]HOST[:PORT]/DEST
  or   rsync [OPTION]... [USER@]HOST:SRC [DEST]
  or   rsync [OPTION]... [USER@]HOST::SRC [DEST]
  or   rsync [OPTION]... rsync://[USER@]HOST[:PORT]/SRC [DEST]
The ':' usages connect via remote shell, while '::' & 'rsync://' usages connect
to an rsync daemon, and require SRC or DEST to start with a module name.

Options
 -v, --verbose               increase verbosity
     --info=FLAGS            fine-grained informational verbosity
     --debug=FLAGS           fine-grained debug verbosity
     --msgs2stderr           special output handling for debugging
 -q, --quiet                 suppress non-error messages
     --no-motd               suppress daemon-mode MOTD (see manpage caveat)
 -c, --checksum              skip based on checksum, not mod-time & size
 -a, --archive               archive mode; equals -rlptgoD (no -H,-A,-X)
     --no-OPTION             turn off an implied OPTION (e.g. --no-D)
 -r, --recursive             recurse into directories
 -R, --relative              use relative path names
     --no-implied-dirs       don't send implied dirs with --relative
 -b, --backup                make backups (see --suffix & --backup-dir)
     --backup-dir=DIR        make backups into hierarchy based in DIR
     --suffix=SUFFIX         set backup suffix (default ~ w/o --backup-dir)
 -u, --update                skip files that are newer on the receiver
     --inplace               update destination files in-place (SEE MAN PAGE)
     --append                append data onto shorter files
     --append-verify         like --append, but with old data in file checksum
 -d, --dirs                  transfer directories without recursing
 -l, --links                 copy symlinks as symlinks
 -L, --copy-links            transform symlink into referent file/dir
     --copy-unsafe-links     only "unsafe" symlinks are transformed
     --safe-links            ignore symlinks that point outside the source tree
     --munge-links           munge symlinks to make them safer (but unusable)
 -k, --copy-dirlinks         transform symlink to a dir into referent dir
 -K, --keep-dirlinks         treat symlinked dir on receiver as dir
 -H, --hard-links            preserve hard links
 -p, --perms                 preserve permissions
 -E, --executability         preserve the file's executability
     --chmod=CHMOD           affect file and/or directory permissions
 -A, --acls                  preserve ACLs (implies --perms)
 -X, --xattrs                preserve extended attributes
 -o, --owner                 preserve owner (super-user only)
 -g, --group                 preserve group
     --devices               preserve device files (super-user only)
     --specials              preserve special files
 -D                          same as --devices --specials
 -t, --times                 preserve modification times
 -O, --omit-dir-times        omit directories from --times
 -J, --omit-link-times       omit symlinks from --times
     --super                 receiver attempts super-user activities
     --fake-super            store/recover privileged attrs using xattrs
 -S, --sparse                handle sparse files efficiently
     --preallocate           allocate dest files before writing them
 -n, --dry-run               perform a trial run with no changes made
 -W, --whole-file            copy files whole (without delta-xfer algorithm)
 -x, --one-file-system       don't cross filesystem boundaries
 -B, --block-size=SIZE       force a fixed checksum block-size
 -e, --rsh=COMMAND           specify the remote shell to use
     --rsync-path=PROGRAM    specify the rsync to run on the remote machine
     --existing              skip creating new files on receiver
     --ignore-existing       skip updating files that already exist on receiver
     --remove-source-files   sender removes synchronized files (non-dirs)
     --del                   an alias for --delete-during
     --delete                delete extraneous files from destination dirs
     --delete-before         receiver deletes before transfer, not during
     --delete-during         receiver deletes during the transfer
     --delete-delay          find deletions during, delete after
     --delete-after          receiver deletes after transfer, not during
     --delete-excluded       also delete excluded files from destination dirs
     --ignore-missing-args   ignore missing source args without error
     --delete-missing-args   delete missing source args from destination
     --ignore-errors         delete even if there are I/O errors
     --force                 force deletion of directories even if not empty
     --max-delete=NUM        don't delete more than NUM files
     --max-size=SIZE         don't transfer any file larger than SIZE
     --min-size=SIZE         don't transfer any file smaller than SIZE
     --partial               keep partially transferred files
     --partial-dir=DIR       put a partially transferred file into DIR
     --delay-updates         put all updated files into place at transfer's end
 -m, --prune-empty-dirs      prune empty directory chains from the file-list
     --numeric-ids           don't map uid/gid values by user/group name
     --usermap=STRING        custom username mapping
     --groupmap=STRING       custom groupname mapping
     --chown=USER:GROUP      simple username/groupname mapping
     --timeout=SECONDS       set I/O timeout in seconds
     --contimeout=SECONDS    set daemon connection timeout in seconds
 -I, --ignore-times          don't skip files that match in size and mod-time
 -M, --remote-option=OPTION  send OPTION to the remote side only
     --size-only             skip files that match in size
     --modify-window=NUM     compare mod-times with reduced accuracy
 -T, --temp-dir=DIR          create temporary files in directory DIR
 -y, --fuzzy                 find similar file for basis if no dest file
     --compare-dest=DIR      also compare destination files relative to DIR
     --copy-dest=DIR         ... and include copies of unchanged files
     --link-dest=DIR         hardlink to files in DIR when unchanged
 -z, --compress              compress file data during the transfer
     --compress-level=NUM    explicitly set compression level
     --skip-compress=LIST    skip compressing files with a suffix in LIST
 -C, --cvs-exclude           auto-ignore files the same way CVS does
 -f, --filter=RULE           add a file-filtering RULE
 -F                          same as --filter='dir-merge /.rsync-filter'
                             repeated: --filter='- .rsync-filter'
     --exclude=PATTERN       exclude files matching PATTERN
     --exclude-from=FILE     read exclude patterns from FILE
     --include=PATTERN       don't exclude files matching PATTERN
     --include-from=FILE     read include patterns from FILE
     --files-from=FILE       read list of source-file names from FILE
 -0, --from0                 all *-from/filter files are delimited by 0s
 -s, --protect-args          no space-splitting; only wildcard special-chars
     --address=ADDRESS       bind address for outgoing socket to daemon
     --port=PORT             specify double-colon alternate port number
     --sockopts=OPTIONS      specify custom TCP options
     --blocking-io           use blocking I/O for the remote shell
     --stats                 give some file-transfer stats
 -8, --8-bit-output          leave high-bit chars unescaped in output
 -h, --human-readable        output numbers in a human-readable format
     --progress              show progress during transfer
 -P                          same as --partial --progress
 -i, --itemize-changes       output a change-summary for all updates
     --out-format=FORMAT     output updates using the specified FORMAT
     --log-file=FILE         log what we're doing to the specified FILE
     --log-file-format=FMT   log updates using the specified FMT
     --password-file=FILE    read daemon-access password from FILE
     --list-only             list the files instead of copying them
     --bwlimit=RATE          limit socket I/O bandwidth
     --outbuf=N|L|B          set output buffering to None, Line, or Block
     --write-batch=FILE      write a batched update to FILE
     --only-write-batch=FILE like --write-batch but w/o updating destination
     --read-batch=FILE       read a batched update from FILE
     --protocol=NUM          force an older protocol version to be used
     --iconv=CONVERT_SPEC    request charset conversion of filenames
     --checksum-seed=NUM     set block/file checksum seed (advanced)
 -4, --ipv4                  prefer IPv4
 -6, --ipv6                  prefer IPv6
     --version               print version number
(-h) --help                  show this help (-h is --help only if used alone)

Use "rsync --daemon --help" to see the daemon-mode command-line options.
Please see the rsync(1) and rsyncd.conf(5) man pages for full documentation.
See http://rsync.samba.org/ for updates, bug reports, and answers
rsync error: syntax or usage error (code 1) at ../rsync-3.1.2/main.c(1551) [client=3.1.2]
root@imx6ul-var-dart:/tmp#

**Is I missing something else on my remote system?**

**Comment by lukka** [comment] 2018-07-03 19:05
Is rsync command is avail in the PATH environment variable? 
Could you please provide both the PATH and the location of the rsync command?
Are you using the root user in the VS's Connection Manager too?

**Comment by lukka** [comment] 2018-07-06 20:29
@boskars Could you please provide these information:
 - What is the target system?
 - Is the provided rsync executable supporting daemon mode?

**Comment by boskars** [comment] 2018-07-09 07:10
@lukka , my target system is:

http://variwiki.com/index.php?title=DART-6UL_Yocto&release=RELEASE_MORTY_V1.0_DART-6UL

I can start rsync in daemon mode as shown here:

root@imx6ul-var-dart:~# rsync --daemon
root@imx6ul-var-dart:~# cat /var/run/rsyncd.pid
490

**Comment by lukka** [comment] 2018-08-30 19:10
Problem should be fixed, it will be in the next Visual Studio Preview release.
Please let us know, thanks!

**Comment by PrecisionWaveRF** [comment] 2018-09-01 22:30
I have the same issue with rsync on VS 2017 enterprise 15.8.2
rsync is correctly installed and running on the target machine but VS can not "start the command"

**Comment by devinvisible** [comment] 2018-09-04 21:27
I'm also seeing the same issue described above.

```
root@74d91bc3b5e9:/# rsync --version
rsync  version 3.1.2  protocol version 31
```
```
root@74d91bc3b5e9:/# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
root@74d91bc3b5e9:/# find -name "rsync"
./etc/default/rsync
./etc/init.d/rsync
./usr/bin/rsync
./usr/share/lintian/overrides/rsync
./usr/share/doc/rsync
```
```
root@74d91bc3b5e9:/# cat /etc/issue.net
Debian GNU/Linux 9
root@74d91bc3b5e9:/# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@74d91bc3b5e9:/# uname -a
Linux 74d91bc3b5e9 4.9.93-linuxkit-aufs #1 SMP Wed Jun 6 16:55:56 UTC 2018 x86_64 GNU/Linux
```

**Comment by lukka** [comment] 2018-09-05 19:48
Please note that the next version of Visual Studio Preview will be 15.9 Preview 3. No public ETA yet.

**Comment by boskars** [comment] 2018-09-06 07:02
Currently the next version for us in the outside world is 15.9 Prev 2, will this fix in the version after the next version?

**Comment by alex4998** [comment] 2018-09-08 06:02
Is there a workaround until the fix is released? Will the fix work for

Linux OpenWrt 4.14.68 #0 SMP Fri Sep 7 15:21:24 2018 i686 GNU/Linux

**Comment by devinvisible** [comment] 2018-10-13 02:00
Visual Studio Preview 15.9 Preview 3 is out. I didn't see this issue mentioned in the release notes. Did this make the cut?

**Comment by itodirel** [comment] 2018-11-27 01:54
Hi, we have seen an issue like that before, is it possible you're antivirus blocks it?

**Comment by boskars** [comment] 2018-11-29 11:41
It can write the c_defines.txt, c_includes.txt, cpp_defines.txt etc and create the whole empty folder structure for the header files.
I do not think the antivirus is causing this, at least I do not get any reports from the antivirus, Microsoft Defender.

**Comment by boskars** [comment] 2018-12-12 11:37
There is still same problem with empty folders in VS2019 prev 1.1

**Comment by itodirel** [comment] 2019-01-15 08:57
we are aware of this issue and are investigating

**Comment by boskars** [comment] 2019-02-18 10:44
Apperently this problem does not have a high priority, there is still same problem in VS2019 prev 3
I am glad I still have v15.7.4 where intellisense is working for me.

**Comment by itodirel** [comment] 2019-03-19 04:12
we've seen this problem when rsync processes would not be correctly closed, we believe this should be fixed now, please install the latest VS preview from here https://visualstudio.microsoft.com/vs/preview/

**Comment by boskars** [comment] 2019-03-19 13:27
This still a problem for me in in VS 16.0.0 Preview 4.2,  all header folders are empty.

**Comment by devinvisible** [comment] 2019-04-04 18:47
I can't imagine it, but did this happened to get resolved in the VS 2019 GA?

**Comment by boskars** [comment] 2019-04-05 06:11
I have not installed it as I do not expect it is resolved.  I am still using VS2017 v15.7.4

**Comment by boskars** [comment] 2019-05-03 09:02
I have found the reason why it was not working:  
VS2019 is executing repeatedly the command:
ps aux
My system does not support the parameters aux.  The ps command is a parameter to BusyBox and BusyBox ps does not support aux.

**Comment by lukka** [comment] 2019-05-14 01:46
@boskars thanks a lot for the report. Could you please create a feedback ticket on Developer Community, just link back to this thread with the explanation of the problem?
Thanks a lot for your support!

**Comment by itodirel** [comment] 2020-03-24 04:34
We believe we have addressed the issue here in the latest version of VS. If this is still a problem for you, please open a issue for us on the Developer Community, as per Luca above.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-24 04:34 UTC
Labels: fixed, investigating
