### ISSUE TITLE
Remote Header Downloads error with Ubuntu 17.10 Server

### ISSUE THREAD

**Issue by ImpossibleMushroom** [Microsoft/VSLinux#279] opened 2018-04-09 21:43 UTC
I am trying to sync the headers from my Ubuntu 17.10 Server VM to my IntelliSense for Remote Compilation so that I can use sys/socket.h, but it is failing each time.

For expected results I am not sure exactly what happens because despite my tries it fails every time, but I'd assume somewhere along the lines of the headers actually syncing

It says that it's failed and to check the log file where I am met with this error each time:
```
liblinux.ExceptionBase: Exception of type 'liblinux.ExceptionBase' was thrown.
   at liblinux.Services.RemoteCompiler.CreateSysrootArchive()
   at liblinux.Services.RemoteCompiler.DownloadSysroot()
   at liblinux.Services.RemoteCompiler.CreateSysroot()
   at liblinux.Services.RemoteCompiler.CreateLocalSysroot()
   at Microsoft.VisualStudio.Linux.Package.Dialogs.HeaderUpdateDialog.<>c__DisplayClass17_0.<DownloadUpdate>b__0(Object _)
```

Using MSVC 15.7 Preview 3 Attempting to sync from a Ubuntu 17.10 Server VM using GCC 7.2.0

As for reproduction I am just going to the 'Remote Headers InteliSense Manager' clicking the VM's IP and clicking download.

**Comment by itodirel** [comment] 2018-04-11 23:16
this is caused by "zip", which is missing from your system, please install "zip" using apt 

in 15.7 Preview 4 (not yet released), we updated the UI to state exactly what the problem is, so you'll know to install zip; we have plans in the future to use rsync

**Comment by itodirel** [comment] 2018-11-27 01:46
hi, we added enhanced logging for this and also rsync support, please let us know if you still have an issue, and I'd happily reactivate and look into it, we are trying to get the issue list number down, so tentatively closing as fixed

**Closed by itodirel** 2018-11-27 01:46 UTC
Labels: fixed, question
