### ISSUE TITLE
start debug failed, could not load cache

### ISSUE THREAD

**Issue by AuroraDysis** [Microsoft/VSLinux#296] opened 2018-05-26 03:58 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
start debug failed, could not load cache
```log
1> rsync --exclude=CMakeFiles -v -r --exclude=.git --exclude=.vs  /C/Users/auror/Documents/GitHub/RNQNMdesitter2/ rsync://root@localhost:4894/temp
1> sending incremental file list
sent 272880 bytes  received 243270 bytes  206460.00 bytes/sec
1> total size is 22864387  speedup is 44.30
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" -D TBB_DIR=~/libs/tbb2018_20180312oss/cmake -D CMAKE_CXX_COMPILER=/usr/bin/clang++-6.0 "/root/RNQNMdesitter/src/Linux-Debug/CMakeLists.txt";
1> -- Boost version: 1.67.0
1> -- Found the following Boost libraries:
1> --   program_options
1> --   filesystem
1> --   system
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /root/RNQNMdesitter/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Extracted includes paths.
1> Extracted CMake variables.
1> Extracted source files and headers.
1> Extracted global settings.
1> Extracted code model.
1> Collating data ...
1> Target info extraction done.
```
all things work well before I change my CMakeSettings.json
* Expected results
start debug
* Actual results (with build output window contents if applicable)
no build button when I right click the CMakeLists.txt, when I click Start
```
>------ Build started: Project: CMakeLists, Configuration: Debug ------
MSBUILD : error MSB6003: The specified task executable "cmd.exe" could not be run. The working directory "C:\Users\auror\CMakeBuilds\602189717\build\Linux-Debug" does not exist.
```
after I create "C:\Users\auror\CMakeBuilds\602189717\build\Linux-Debug" manully
```
C:\WINDOWS\system32\EXEC : error : could not load cache
```
* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
  - visual studio 15.8.0 preview 1.0
  - clang++ 6.0
  - gdb 8.1
  - cmake 3.11.1
* Steps required to reproduce the error

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by yuehuang010** [comment] 2018-05-29 21:16
Hello, could you share your project or a reduced sample of your project?  Also please share your CMakeSettings.json.
Thanks

**Comment by AuroraDysis** [comment] 2018-05-30 10:42
Sorry, I can't share my project, this is CMakeSettings.json
```json
{
  // See https://go.microsoft.com//fwlink//?linkid=834763 for more information about this file.
  "configurations": [
    {
      "name": "Linux-Debug",
      "generator": "Unix Makefiles",
      "remoteMachineName": "000.00.00.00",
      "configurationType": "Debug",
      "remoteCMakeListsRoot": "~/RNQNMdesitter/src/${name}", //"/var/tmp/src/${workspaceHash}/${name}",
      "cmakeExecutable": "/usr/local/bin/cmake",
      "buildRoot": "${env.USERPROFILE}\\RNQNMdesitter\\RNQNMdesitter\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\RNQNMdesitter\\RNQNMdesitter\\install\\${name}",
      "remoteBuildRoot": "~/RNQNMdesitter/build/${name}", //"/var/tmp/build/${workspaceHash}/build/${name}",
      "remoteInstallRoot": "~/RNQNMdesitter/install/${name}", //"/var/tmp/build/${workspaceHash}/install/${name}",
      "remoteCopySources": true,
      "remoteCopySourcesOutputVerbosity": "Normal",
      "remoteCopySourcesConcurrentCopies": "10",
      "remoteCopySourcesMethod": "rsync",
      "remoteCopyBuildOutput": false,
      "cmakeCommandArgs": "-D TBB_DIR=~/libs/tbb2018_20180312oss/cmake -D CMAKE_CXX_COMPILER=/usr/bin/clang++-6.0",
      "buildCommandArgs": "-j4",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "linux_x64" ],
      "rsyncCommandArgs": "--exclude=CMakeFiles"
    },
    {
      "name": "Linux-Release",
      "generator": "Unix Makefiles",
      "remoteMachineName": "000.00.00.00",
      "configurationType": "Release",
      "remoteCMakeListsRoot": "~/RNQNMdesitter/src/${name}", //"/var/tmp/src/${workspaceHash}/${name}",
      "cmakeExecutable": "/usr/local/bin/cmake",
      "buildRoot": "${env.USERPROFILE}\\CMakeBuilds\\RNQNMdesitter\\build\\${name}",
      "installRoot": "${env.USERPROFILE}\\CMakeBuilds\\RNQNMdesitter\\install\\${name}",
      "remoteBuildRoot": "~/RNQNMdesitter/build/${name}", //"/var/tmp/build/${workspaceHash}/build/${name}",
      "remoteInstallRoot": "~/RNQNMdesitter/install/${name}", //"/var/tmp/build/${workspaceHash}/install/${name}",
      "remoteCopySources": true,
      "remoteCopySourcesOutputVerbosity": "Normal",
      "remoteCopySourcesConcurrentCopies": "10",
      "remoteCopySourcesMethod": "rsync",
      "remoteCopyBuildOutput": false,
      "cmakeCommandArgs": "-D TBB_DIR=~/libs/tbb2018_20180312oss/cmake -D CMAKE_CXX_COMPILER=/usr/bin/clang++-6.0",
      "buildCommandArgs": "-j4",
      "ctestCommandArgs": "",
      "inheritEnvironments": [ "linux_x64" ],
      "rsyncCommandArgs": "--exclude=CMakeFiles"
    }
  ]
}
```
I will try to make a reduced sample when I am free.

**Comment by lukka** [comment] 2018-06-06 14:44
@AuroraDysis this is a duplicate of #297 
The bug is fixed in the next version Visual Studio 2017 Preview 15.8. Closing this and keeping open the other.

**Closed by lukka** 2018-06-06 14:44 UTC
