### ISSUE TITLE
Additional Include Directories not added to Compile arguments consistently.

### ISSUE THREAD

**Issue by johncuyle** [microsoft/VSLinux#264] opened 2018-03-07 22:21 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

Compile command is being incorrectly constructed.  Include directories are getting lost, somehow.  Here's some truncated diagnostic output.

```
1>  Task "MakeClCommandLine"
...
1>    Task Parameter:
1>        AdditionalIncludeDirectories=
**1>            C:\Users\jcuyle\Source\Workspaces\cminussoft\ext\ext\mbimodule_1_0_0\mbimodule\
1>            C:\Users\jcuyle\Source\Workspaces\cminussoft\ext\ext\mbimodule_1_0_0\Mbi\include\**
...
1>    Output Item(s): 
1>        RemoteClCompile=
1>            /home/jcuyle/projects/Mbi.Linux/Mbi/src/String_impl.cpp
1>                    CommandLine=-c -x c++ /home/jcuyle/projects/Mbi.Linux/Mbi/src/String_impl.cpp **-I /home/jcuyle/projects/Mbi.Linux/mbimodule** -g2 -gdwarf-2 -o "/home/jcuyle/projects/Mbi.Linux/obj/x64/Debug/String_impl.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -D_DEBUG -DASSERT_ENABLED=1 -fthreadsafe-statics -fexceptions -fno-rtti -std=c++14
1>                    LocalFileName=C:\Users\jcuyle\Source\Workspaces\cminussoft\ext\ext\mbimodule_1_0_0\Mbi\src\String_impl.cpp
1>                    LocalName=String_impl.cpp
1>                    LocalOutputFileName=C:\Users\jcuyle\Source\Workspaces\cminussoft\ext\ext\mbimodule_1_0_0\obj\x64\Debug\String_impl.o
1>                    OutputFileName=/home/jcuyle/projects/Mbi.Linux/obj/x64/Debug/String_impl.o
1>                    RemoteToolExe=g++
1>  Done executing task "MakeClCommandLine".
```

See bolded text in code snippet.  Expected result is that BOTH directories specified as AdditionalIncludeDirectories will be added to the compile command, not just one of them.

See above.  Build fails due to inability to find a required header, which it can't find because the include path is not specified in the compile command.

> Microsoft Visual Studio Professional 2017 
> Version 15.5.2
> VisualStudio.15.Release/15.5.2+27130.2010
> Microsoft .NET Framework
> Version 4.7.02556
> 
> Installed Version: Professional
> 
> Visual Basic 2017   00369-60000-00001-AA353
> Microsoft Visual Basic 2017
> 
> Visual C# 2017   00369-60000-00001-AA353
> Microsoft Visual C# 2017
> 
> Visual C++ 2017   00369-60000-00001-AA353
> Microsoft Visual C++ 2017
> 
> Application Insights Tools for Visual Studio Package   8.10.01106.1
> Application Insights Tools for Visual Studio
> 
> ASP.NET and Web Tools 2017   15.0.31125.0
> ASP.NET and Web Tools 2017
> 
> Common Azure Tools   1.10
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> GitHub.VisualStudio   2.3.6.391
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JavaScript UWP Project System   2.0
> JavaScript UWP Project System
> 
> Microsoft JVM Debugger   1.0
> Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Visual C++ Wizards   1.0
> Microsoft Visual C++ Wizards
> 
> Microsoft Visual Studio VC Package   1.0
> Microsoft Visual Studio VC Package
> 
> NuGet Package Manager   4.5.0
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> P4VS - Helix Plugin for Visual Studio   2017.2.161.4623
> P4VS is the Perforce Helix integration for Microsoft Visual Studio. P4VS provides developers working within Visual Studio access to Helix version control features, including check in/check out, view file history, and more.
> 
> TypeScript Tools   15.5.11025.1
> TypeScript Tools for Microsoft Visual Studio
> 
> Visual Assist   
> For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2017 Whole Tomato Software, Inc.
> 
> Visual C++ for Linux Development   1.0.8
> Visual C++ for Linux Development
> 
> Visual Studio Code Debug Adapter Host Package   1.0
> Interop layer for hosting Visual Studio Code debug adapters in Visual Studio
> 
> Visual Studio Comparison Tools   1.0
> Information about my package
> 
> Visual Studio Tools for CMake   1.0
> Visual Studio Tools for CMake
> 
> Visual Studio Tools for Universal Windows Apps   15.0.27128.01
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 

Just add a couple include paths and watch them not end up in the compile arguments.  Not all of them anyway.  Not in any predictable manner.

I followed the blog post on configuring for Linux Subsystem for Windows, installing Ubuntu from the store, and installing the Linux build tools through the VS 2017 installer

**Comment by yuehuang010** [comment] 2018-03-15 02:54
Hi, could you please try 15.7 preview 1 to see if your issue still appears?  The release has made many changes to the way translation paths are handled.

**Comment by itodirel** [comment] 2020-03-27 01:18
This issue has been addressed in the latest update of VS. 

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-27 01:18 UTC
Labels: bug
