### ISSUE TITLE
vs2017 build linux project use cmake-Input string was not in a correct format.

### ISSUE THREAD

**Issue by xcyl** [microsoft/VSLinux#317] opened 2018-07-28 09:38 UTC
1> /usr/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "/var/tmp/src/4d72ccab-fac1-1530-8b99-ef6315149803/Linux-Debug/CMakeLists.txt";
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /var/tmp/build/4d72ccab-fac1-1530-8b99-ef6315149803/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.。
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriverBase.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriverBase.<ShakeHandAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsyncImpl>d__29.MoveNext()

local:
Visual Studio 2017 15.7.5
Visual Studio 2017 15.8 Preview 5.0
cmake 3.11.4

remote:
CentOS Linux release 7.3.1611
cmake 3.11.4

**Comment by lukka** [comment] 2018-07-30 18:33
@xcyl could you provide us a repro? We need a small project to build and reprocude that behavior. Have you tried on VS preview 15.8 preview 5?

**Comment by xcyl** [comment] 2018-07-31 16:28
@lukka yes, I tried VS preview 15.8 preview 5,  they have the same problem.
You can try CentOS Linux release 7.3.1611, even the "hello world" program will have this problem.

**Comment by lukka** [comment] 2018-08-02 03:17
@xcyl how did you got cmake 3.11.4 on CentOS 7.3? The yum package manager is reporting cmake 2.8 available only.

Please try with our [prebuilt binary of cmake for Linux](https://github.com/Microsoft/CMake/releases) and report back the result, thanks!

**Comment by lukka** [comment] 2018-08-03 19:51
@xcyl I just used CentOS 7.3 with our prebuilt cmake and it worked with the "hello world" project.

**Comment by xiaol-luo** [comment] 2018-08-23 07:11
I use visual studio 2017 15.9.0 preview 1.0 and in centos7.3.1611 I have tried cmake 3.9.0 cmake 3.12 cmake 3.11 . they all meet the same problem showed above:

error message :
1> Copying files to remote machine...
1> rsync -t --delete --delete-excluded -v -r --exclude=.vs --exclude=.git --exclude=.vs --exclude=.git  /E/git_dir/test/ rsync://root@localhost:49938/temp
1> sending incremental file list
1> ./
1> CMakeLists.txt
1> 
1> sent 354 bytes  received 36 bytes  70.91 bytes/sec
1> total size is 3187  speedup is 8.17
1> Finished copying files.
1> /usr/local/bin/cmake -G "Unix Makefiles"  -DCMAKE_BUILD_TYPE="Debug" "/var/tmp/src/28f1cc8c-26a0-2d33-925f-078f5d72f7df/Linux-Debug/CMakeLists.txt";
1> -- The C compiler identification is GNU 8.1.0
1> -- The CXX compiler identification is GNU 8.1.0
1> -- Check for working C compiler: /usr/local/bin/cc
1> -- Check for working C compiler: /usr/local/bin/cc -- works
1> -- Detecting C compiler ABI info
1> -- Detecting C compiler ABI info - done
1> -- Detecting C compile features
1> -- Detecting C compile features - done
1> -- Check for working CXX compiler: /usr/local/bin/c++
1> -- Check for working CXX compiler: /usr/local/bin/c++ -- works
1> -- Detecting CXX compiler ABI info
1> -- Detecting CXX compiler ABI info - done
1> -- Detecting CXX compile features
1> -- Detecting CXX compile features - done
1> -- Configuring done
1> -- Generating done
1> -- Build files have been written to: /var/tmp/build/28f1cc8c-26a0-2d33-925f-078f5d72f7df/build/Linux-Debug
1> Starting CMake target info extraction ...
1> Target info extraction done.
1> Input string was not in a correct format.
   at System.Text.StringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at libcmake.CMakeDaemonDriverBase.Expects(String message, String expectedMessage)
   at libcmake.CMakeDaemonDriverBase.<ShakeHandAsync>d__38.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeDaemonDriver.<ShakeHandAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.RemoteCMakeLists.<ParseWithoutCacheAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at libcmake.Linux.LocalCMakeLists.<ParseAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsUtils.<ParseAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.VisualStudio.CMake.Project.CMakeListsCache.<ParseAsyncImpl>d__29.MoveNext()

**Comment by xcyl** [comment] 2018-08-27 11:41
@xiaol-luo update your ssh-server

**Comment by theRealRed** [comment] 2018-08-29 05:26
I meet the same issue just as mentioned here with centos 7.3.1611 and cmake 3.11.4. 
Is there any way to fix it please? @xcyl  @lukka

**Comment by lukka** [comment] 2018-09-05 21:31
@xcyl @theRealRed could you please try with the [prebuilt binary of CMake for Linux](https://github.com/Microsoft/CMake/releases) and report back the result, thanks!

**Comment by theRealRed** [comment] 2018-09-11 08:53
@lukka I tried cmake-3.11.18033000-MSVC_2-Linux-x86_64.sh, not work, same exception throwed.
@xcyl I check the current ssh-server, it's openssh-server.x86_64, version 6.6.1p1-33.el7_3.  I'd update it to a later version and try again.

**Comment by haoyixin** [comment] 2018-09-25 05:29
@theRealRed what's the result?

**Comment by haoyixin** [comment] 2018-09-25 05:54
@lukka it's still not working with your prebuilt cmake and newest sshd in latest vs.

**Comment by lyandut** [comment] 2019-09-14 05:31
i solved this problem after upgraded ssh-server to OpenSSH_7.5p1 with Centos 6.10 and cmake 3.15.2940156-MSVC_2.

**Comment by itodirel** [comment] 2020-03-24 04:45
We believe this should be fixed now. If it's due to a shell configuration it is tracked with, and planned to be addressed, in our roadmap: https://developercommunity.visualstudio.com/idea/956725/compatibility-with-other-shells.html

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-24 04:45 UTC
Labels: need repro
