### ISSUE TITLE
How to debug issues with IDE not finding include files

### ISSUE THREAD

**Issue by rkeithhill** [microsoft/VSLinux#188] opened 2017-09-20 23:15 UTC
Please use the following bug reporting template to help produce actionable and reproducible issues:

* A brief description
Our CMake based folder builds just fine but in the IDE when I view files I see red all over the place because header files aren't found (cannot open source file QtCore/QtVector).  This may be because these header files are coming from a conan package.  However it doesn't make sense that the build would be able to find the header files but the editor can't.

* Expected results
I should not see all the red error squiggles in the editor.  The editor should be able to find the header files if the build can find them.

* Actual results (with build output window contents if applicable):
![image](https://user-images.githubusercontent.com/5177512/30672073-66f57fe8-9e27-11e7-905a-f23d8e66be19.png)

* VC++ version, Linux system name and version, GCC/GDB/gdbserver version, CPU arch, etc. If you are using a specific version of Linux on an embedded board, we might need to know about it to get a repro on similar hardware
Windows 10 1703 64-bit with VS 2017 Update 15.3.5.

* Steps required to reproduce the error
Not sure but I think it involves referencing conan package dirs from the CMakeLists.txt file e.g.:
```
INCLUDE_DIRECTORIES(${CONAN_INCLUDE_DIRS})
```

* Required packages and commands to install

See [our contributing instructions](/CONTRIBUTING.md) for assistance.

**Comment by rkeithhill** [comment] 2017-09-20 23:27
I found a [way ](https://stackoverflow.com/questions/6902149/listing-include-directories-in-cmake) to dump the INCLUDE_DIRECTORIES defined in the CMakeLists.txt file.  It has this entry:
```
1> -- dir='C:/.conan/9o84py7o/1/include/QtCore'
```
Sure enough, there is a `QtVector` file in that dir with these contents:
```
#include "qvector.h"
```
And there is a qtvector.h file in this same directory.

**Comment by rkeithhill** [comment] 2017-09-20 23:45
And if I right-click the red squiggle, I get this:
![image](https://user-images.githubusercontent.com/5177512/30672733-76ca459e-9e2b-11e7-942c-5e182a97b8a7.png)
Why aren't the CMake's INCLUDE_DIRECTORIES listed here?

**Comment by itodirel** [comment] 2019-03-21 05:58
I think this is a bug that we fixed, please install the latest VS 2019 preview

For IntelliSense problems, you can enable IntelliSense logging from Tools - Options - Text Editor - C/C++ - Advanced - Diagnostic Logging, set Logging to True, and Logging Filter to 8, restart VS, logging will be in Output Window. Reproduce the scenario, and the Output Window will contain the include directories passed to the IntelliSense compiler.

**Comment by itodirel** [comment] 2020-03-20 21:08
We have addressed a lot of bugs with IntelliSense errors, and we believe this was addressed as well, please update to the latest version and latest update of VS 2019. If this is still an issue, please open a issue for  us on the Developer Community.

We have retired this issue list, here on Github. We now adopted and are using the Developer Community (https://developercommunity.visualstudio.com/spaces/62/index.html), for Cross Plat and Linux experiences (and C++ all up generally), which we are actively monitoring. Please use the Developer Community, to report issues or suggestions for bugs or new experiences. Further discussions on this thread here on Github might be unmonitored. If there is further comments or context to this current issue, please create a new issue on the Developer Community, and provide the context there. For any existing issues, which we can or able to reproduce, or for anything that is actionable to us and understood, we will provide an update right here in this thread. Additionally, for new suggestions or new issues, which at this time are in our roadmap, or for which we believe and have evidence that broadly and/or significantly benefit everyone, we will open a suggestion ticket, and link it here. For anything else, we recommend to please open a ticket on the Developer Community. That isn't because we will not look at the problem, or not investigate it otherwise, but simply because we need additional information. And for features, we are tracking them on the Developer Community.

**Closed by itodirel** 2020-03-20 21:08 UTC
Labels: question
