### ISSUE TITLE
bash: -c: command not found

### ISSUE THREAD

**Issue by pps83** [Microsoft/VSLinux#160] opened 2017-07-24 02:37 UTC
When I compile I get occasionally `bash: -c: command not found`. Sometimes it works, sometimes fails and I see that nonsense in the log (see highlighted text):

1>  Task "Compile"
1>    Starting remote build
1>    Compiling sources:
1>    Invoking g++
1>     -c "/home/pps/projects/test-proxy/proxy.cpp" -g2 -gdwarf-2 -o "/home/pps/projects/test-proxy/obj/x64/Debug/proxy.o" -Wall -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-pointer-sign" -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -Wswitch -W"no-deprecated-declarations" -W"empty-body" -Wconversion -W"return-type" -Wparentheses -W"no-format" -Wuninitialized -W"unreachable-code" -W"unused-function" -W"unused-value" -W"unused-variable" -O0 -fno-strict-aliasing -fno-omit-frame-pointer -fthreadsafe-statics -fexceptions -frtti -std=c11 -std=c++11 -Wno-conversion
1>    proxy.cpp
1>    `bash: -c: command not found`
1>    `bash: -c: command not found`
1>    Done compiling '/home/pps/projects/test-proxy/proxy.cpp'
1>    C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VC\VCTargets\Application Type\Linux\1.0\Linux.targets(248,5): error :  exited with code 127, please see the Output Window - Build output for more details (`NOTE: the build output verbosity might need to be changed in Tools Options to see more information in the Output Window`).
1>  Done executing task "Compile" -- FAILED.
1>Done building target "ClCompile" in project "test-proxy.vcxproj" -- FAILED.

that note about verbosity is complete joke, it doesn't have any effect and produces exactly the same output.

When this command works, I see `g++ -c -x c++ "/home/pps/projects/test-proxy/proxy.cpp" -g2 ...`. Somehow your code fails randomly and doesn't runs some empty command instead of g++??

Can you please test on links that have 200ms + ping time?.. lots of room for improvements.

**Comment by pps83** [comment] 2017-07-24 05:03
looks like Ctrl+F7 (compile a file) triggers this bug. Vs2015 plugin and VS2017 have the same problem

**Comment by stanthomas** [comment] 2017-07-24 16:52
Long standing issue, see #5 .

**Comment by braindeaddeveloper** [comment] 2017-08-04 16:24
Guys ! anyone there looking at this ???? An update would be polite !! its a real pain and colleagues are beginning to ask why one bothers to soldier on with VSLinux.

**Comment by itodirel** [comment] 2017-08-09 23:39
closing as a duplicate of 167

**Comment by itodirel** [comment] 2017-08-09 23:39
I tagged 167 as a bug

**Closed by itodirel** 2017-08-09 23:39 UTC
