### ISSUE TITLE
Unable to debug

### ISSUE THREAD

**Issue by afshinpir** [Microsoft/VSLinux#94] opened 2017-01-22 10:59 UTC
Hi

I started to use version 1.0.6 of this extension yesterday. It is a great tool for building you cross platform code, but I have a strange problem with debugging. I have setup my connection correctly and I can connect to my Linux host and build my application (right now, just sample that you get when create new "Console Application (Linux)").
But when I try to debug my code, I see an immediate error which says:
"unable to start debugging. Check your debugger settings by opening ..."
I wonder what the problem is. I can connect and build this small code and I have even run application on remote Linux host with no problem. There is build screenshot:
![build](https://cloud.githubusercontent.com/assets/13680164/22181969/d72da688-e0ad-11e6-836d-841210a88acc.png)

There is nothing special in my project properties. But I should say that there is no "Remote settings" in project settings in contrast to available tutorial screenshots. Here is a screenshot:
![prop](https://cloud.githubusercontent.com/assets/13680164/22181973/11a564a4-e0ae-11e6-884c-5dab51d464c7.png)

It will be great if you could provide some inside for this problem.
Best Regards

Here are version details:
Visual Studio 2015 & VsLinux 1.0.6
Ubuntu 14.04 x64
gdb & gdbserver 7.7.1

**Comment by tommitytom** [comment] 2017-01-27 12:36
Also having this issue, no "Remote Settings" option!

**Comment by IdoTene** [comment] 2017-02-16 12:21
I'm experiencing the same here, I'm adding here the packages data for the dev team:
Microsoft Visual Studio Professional 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Professional

Visual Basic 2015   00325-60004-10919-AA551
Microsoft Visual Basic 2015

Visual C# 2015   00325-60004-10919-AA551
Microsoft Visual C# 2015

Visual C++ 2015   00325-60004-10919-AA551
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00325-60004-10919-AA551
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20626.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Debugging Tools for Windows   10.0.10011.16384
Integrates the Windows Debugger functionality (http://go.microsoft.com/fwlink/?linkid=223405) in Visual Studio.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

KofePackagePackage Extension   1.0
KofePackagePackage Visual Studio Extension Detailed Info

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

NuGet Package Manager   3.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Visual C++ for Linux Development   1.0.6
Visual C++ for Linux Development

Windows Driver Kit   10.0.10011.16384
Headers, libraries, and tools needed to develop, debug, and test Windows drivers (msdn.microsoft.com/en-us/windows/hardware/gg487428.aspx)

Windows Installer XML Toolset   3.10.0.2103
Windows Installer XML Toolset version 3.10.0.2103
Copyright (c) Outercurve Foundation. All rights reserved.

Workflow Manager Tools 1.0   1.0
This package contains the necessary Visual Studio integration components for Workflow Manager.

Xamarin   3.11.1589.0 (f119127)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin.Android   5.1.7.12 (53fce3730830417896a42f365a5ba35f1ee58d9d)
Visual Studio plugin to enable development for Xamarin.Android.

Xamarin.Forms Intellisense   1.0
Provides intellisense for Xamarin.Forms in the XML editor.

Xamarin.iOS   9.1.0.0 (a49a79c0e30fc5f9acf323008a9e44be2f0c1bd2)
Visual Studio extension to enable development for Xamarin.iOS.

Xamarin.iOS Unified Migration   1.0
Automated migration for Xamarin iOS Classic projects to Unified

Xamarin.TestCloud.Integration   1.0
Early preview of Xamarin Test Cloud integration

**Comment by robotdad** [comment] 2017-03-02 17:07
Apologies the docs fell behind the implementation. The remote settings property page was removed, those settings moved to the general property page. I'll be updating the docs next week with the VS2017 release.

I'm not aware of any issues with the Ubuntu system you cite connecting to. Can you get us a log per the instructions here: https://github.com/Microsoft/MIEngine/wiki/Logging

**Comment by afshinpir** [comment] 2017-03-03 06:11
@robotdad 

Hi
I tried to use that link for enabling debugging but I got an error:

```
d:\Codes\MIEngine-master\src\MICore>SetMIDebugLogging.cmd on
ERROR: The found version(s) of Visual Studio do not have the MIEngine installed.
```

I think something is wrong. I thought VSLinux is using this engine and this command will enable debugging. But it seems not. Do I need to install MIEngine separately too?

Regards

**Comment by paulmaybee** [comment] 2017-03-09 23:37
Is Visual Studio installed in the usual location (C:\Program Files (x86)\Microsoft Visual Studio 14.0)? If not then you need to add a /VSRootDir parameter pointing to the install location.

**Comment by afshinpir** [comment] 2017-03-12 06:27
@paulmaybee 

Oh,yea. I'm sorry.
My VS is not installed in default directory (it is in D:). I enabled MIEngine's debugging, but I should say that no log file is generated. When I try to debug, I get error message really quickly, and it feels like that it does not even try to connect my remote Ubuntu for debugging (everything is OK for building, problem is just for debugging).

Regards

**Comment by itodirel** [comment] 2017-03-13 22:02
@afshinpir what do you see if you got to the General page in the Property Pages and look under Remote Build Machine, is the field empty?

**Comment by afshinpir** [comment] 2017-03-17 06:25
@itodirel 
Hi

Yes, 'Remote Build Machine' field is empty. But build process was working, so I thought being empty is normal.

**Comment by basabuber** [comment] 2017-04-16 06:23
I think I am encountering a duplicate of this issue. The problem should be easy to reproduce. It seems that for the remote debugging, it is using 127.0.0.1 and port 4444 to talk to gdbserver rather than the correct remote ip xx:xx:xx:xx. Linux Console Window shows host 127.0.0.1.

**Comment by itodirel** [comment] 2017-04-28 04:06
Hi, I believe this is caused by a corrupt MEF cache. Can you close all instances of Visual Studio, delete the %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache folder and all its contents, entirely from disk.  Open a Developer Command Prompt for VS2015, you should be able to find or search for it in the Windows start menu, there run devenv /updateConfiguration. Start Visual Studio again.

**Comment by afshinpir** [comment] 2017-04-28 06:32
@itodirel 

I tried this approach. It is still not working.

**Comment by bruceoberg** [comment] 2017-05-16 20:41
@itodirel 

Deleting the MEF cache fixed this problem for me.

**Comment by itodirel** [comment] 2017-08-21 23:40
@afshinpir  can you confirm this is still not working for you?

**Comment by itodirel** [comment] 2017-09-19 21:32
Closing due to inactivity, for tracking purposes, if this is still a problem, please reactive or just ping us and we'll reactivate.

**Closed by itodirel** 2017-09-19 21:32 UTC
Labels: investigating
