### ISSUE TITLE
Connection Manager: Host name has to be equal to IP address

### ISSUE THREAD

**Issue by jensreck** [Microsoft/VSLinux#250] opened 2018-01-17 14:48 UTC
The host name and so the 'environment variable' for the setting "remoteMachineName" has to be equal to the IP address. So it's not possible to use different VMs with different ports and same (local) IP.
If the IP address of various VMs are equal (and the ports are different), tasks and launch configuration use always the first entry.

The better solution is to add a user defined 'connection name' string in additional to distinguish different connections / VMs.

Microsoft Visual Studio Professional 2017 Preview
Version 15.6.0 Preview 2.0
VisualStudio.15.Preview/15.6.0-pre.2.0+27309.0
Microsoft .NET Framework
Version 4.7.02046

**Comment by itodirel** [comment] 2018-01-18 04:28
We support multiple machines simultaneously, in that any project can select a specific remote target, this can be done as shown in the attached images:

![pic1](https://user-images.githubusercontent.com/15239856/35080814-e2ac1988-fc07-11e7-8ba2-57c7eb9fdc63.png)

![pic2](https://user-images.githubusercontent.com/15239856/35080789-b4b70a10-fc07-11e7-8441-93a267603705.png)

**Comment by jensreck** [comment] 2018-01-18 08:35
Sorry but I can not create a connection without IP address (in a CMake project)...

Connection with IP:
![2018-01-18_09h27_29_connection_ok](https://user-images.githubusercontent.com/6204503/35088075-bcc366f6-fc32-11e7-9214-2eb5229c2b26.png)

Connection with name:
![2018-01-18_09h27_29_connection_set](https://user-images.githubusercontent.com/6204503/35088096-cc647be0-fc32-11e7-8f27-de0fb9f66cd9.png)
![2018-01-18_09h27_47_connection_failed](https://user-images.githubusercontent.com/6204503/35088098-cfeeb12c-fc32-11e7-8486-f8e4a2b645b9.png)

**Comment by iontodirel** [comment] 2018-01-18 09:04
I see, that would mean that the remote system is not accessible by host name, is this WSL? does it work with a program like Putty?

**Comment by jensreck** [comment] 2018-01-18 09:34
its a VBox (Linux Mint 18.2) and I have create both configuration step by step meaning starts with 127.0.0.1... it works and immediate after this I try to add the second connection "host42".

**Comment by itodirel** [comment] 2018-01-18 20:29
it depends on how your Linux machine is configured, IIRC Linux Mint had problems with DNS and it was always difficult to access it using a hostname; I can't provide guidance for that specifically, I would refer to the Mint documentation here, but it seems like the problem is on your Linux machine

**Comment by itodirel** [comment] 2018-01-18 22:54
Oh, one question I have, is this in the context of CMake or MSBUILD and vcxproj?

**Comment by jensreck** [comment] 2018-01-19 09:34
We use a CMake project.

**Comment by itodirel** [comment] 2018-01-19 22:24
Ah I see, that then explains it

**Comment by itodirel** [comment] 2018-04-05 20:51
yes, we need to support a way to disambiguate between different host names that might be the same, but can have different ports, or users or authentication methods

**Comment by vermosen** [comment] 2018-05-31 23:28
Hi, 
@iontodirel: I personally use PuTTY with a centos remote machine and it all works fine. 

One of the problem is that the $(RemoteTarget) variable has a pretty clumsy format and currently looks as stated above:
-1647985512;HOSTNAME (username=abc, port=22, authentication=Password)

It is possible to extract the host name in the prebuild/postbuild events with the snippet below, but that would be great to break the sting down in separate variables.
Jm

set node=
call :getNode node $(RemoteTarget)
....
EXIT /B

:getNode
set %~1=%~3
goto:EOF

**Comment by itodirel** [comment] 2018-11-27 01:45
Hi, we added support to disambiguate the connection in CMake projects, it is coming in 16.0 Preview 2.

**Comment by VMinute** [comment] 2018-12-06 15:35
Just a quick and nasty workaround, if someone may need it while waiting for 16.0 Preview 2 (I do).
I need to connect to multiple containers running on my machine, so I have many connections all named 127.0.0.1. I notice that VS seems to consider names always as strings (makes sense) so 127.0.0.1 is not the same as 127.0.0.01 (and so on), in this way you can have multiple connections to the same IP with different names.

**Comment by itodirel** [comment] 2019-01-18 09:09
@VMinute thank you for your patience with us

**Comment by itodirel** [comment] 2019-03-19 04:00
closed as fixed, no plans in backporting

**Closed by itodirel** 2019-03-19 04:00 UTC
Labels: enhancement, fixed
